- README.rst
This should make it possible for people to find our more detailed documentation.
https://github.com/Instagram/LibCST/blob/18b513d61f322cf2cdfdb859ab148a49349bb4dc/README.rst
> Link to ReadTheDocs from our README file

- .readthedocs.yml
> [readthedoc] install libcst

- libcst/_visitors.py
As written, the docs are wrong. Fix it to be the correct behavior.
tox
> Fix incorrect description of on_leave for CSTVisitor/CSTTransform.

- README.rst
add PYPI version badge to readme
> add PYPI version badge to readme

- libcst/_nodes/_internal.py
> Document where CodeRange is inclusive/exclusive

- libcst/_nodes/_internal.py
- libcst/_nodes/tests/base.py
- libcst/_nodes/tests/test_cst_node.py
- libcst/_nodes/tests/test_removal_behavior.py
- libcst/_parser/_entrypoints.py
- libcst/_types.py
- libcst/_visitors.py
refactor TypeVar CSTNodeT for consistency and reusability
CI builds.
> [typing] refactor TypeVar CSTNodeT for consistency and reusability

- requirements-dev.txt
Pin hypothesis library version to work around https://github.com/Zac-HD/hypothesmith/issues/3
tox
> Pin Hypothesis

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_position_provider.py
Some minor improvements
1. batch isinstance calls.
2. avoid redefine builtin functions.
> Some minor improvements

- libcst/metadata/__init__.py
As it says on the tin! Export this so that people can type their visitors.
tox, eyes.
> Export ProviderT so it can be used to type METADATA_DEPENDENCIES.

- libcst/metadata/expression_context_provider.py
- libcst/metadata/tests/test_expression_context_provider.py
Nested List and Tuple are not analyzed correctly previously.
E.g. when nested List or Tuple used as assignment targets, all simple Name in List or Tuple should have STORE context.
In `((a, b), c) = ((1, 2), 3)`, name a/b/c has STORE context. Same for `[[a, b], c] = [[1, 2], 3]`
In LibCST, Attribute.attr is a Name but it's a str in ast.
In ast expression context, Name has LOAD context when it is a local variable. To honor that, we only set context to left most Name in attribute access.
E.g. In `a.b.c = 1`, only Name("a") has STORE context, b/c has None as context.
New added Assignments and Accesses APIs.
https://github.com/Instagram/LibCST/pull/93/commits/a0557123f309c925ecf0a86507e8af1376421817
Unit  tests.
> rewrite ExpressionContextProvider to handle nested List/Tuple and Attribute

- libcst/codegen/gen_matcher_classes.py
- libcst/matchers/_matcher_base.py
> Add missing license header to matchers generator file.

- libcst/matchers/_matcher_base.py
use list instead of tuple for sequence in docs for readability
https://3131-200896124-gh.circle-artifacts.com/0/doc/index.html
> use list instead of tuple for sequence in docs for readability

- CHANGELOG.md
- setup.py
> Bump version to 0.2.1

- libcst/_nodes/base.py
- libcst/tests/test_deep_replace.py
This allows you to do in one helper what you previously needed to combine a `with_changes` and `deep_replace` helper call to do. This addresses #107.
new test added, tox
> Add a 'with_deep_changes' helper method

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_qualified_name_provider.py
Optional[Collection[QualifiedName]] -> Collection[QualifiedName]
pyre
> [metadata] make QualifiedNameProvider typing more specific

- libcst/metadata/scope_provider.py
While cleaning up wiki pages, I found this example was useful for explaining why `Scope.__getitem__` returns a list. So move it to here.
> [doc] improve documentation of Scope.__getitem__

- libcst/_nodes/base.py
It turns out that when we had a sequence type, like Module's body, we were incorrectly
leaning on copy.deepcopy for the rest of the tree. This works, but its likely to blow
the stack when doing a deep clone of a very very large file. Fix that oversight here.
`tox`
> Fix deep_clone for sequence types

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
add FunctionDef and ClassDef to FunctionScope and ClassScope
In a recent use case, the user wanted to get the node defines the scope and she had to do `scope.parent[scope.name]`. That returns a list of possible Assignments contain FucntionDef/ClassDef nodes.
If we just store the node in scope object, it's simple and accurate as `scope.node`
CC @bgw 
Unit test.
> [scope] add node to LocalScope

- docs/source/best_practices.rst
- docs/source/index.rst
- libcst/_helpers.py
There are going to be many more where this comes from, but these are the three cases that have come up most frequently, so I started with these. Hopefully this helps give additional direction to people using LibCST.
`tox -e docs`
> Add a best practices section with various recommended practices

- CHANGELOG.md
- README.rst
- setup.py
As it says on the tin! Update the readme, setup.py and changelog.
Eyes?
> Bump LibCST to 0.2.2.

- docs/source/matchers.rst
- libcst/matchers/_matcher_base.py
Update documentation on sequence matchers based on some user feedback and initial confusion. Hopefully the new documentation is more clear.
tox
> Update matchers docs with some clarification based on user feedback

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
add qualified name support for imported attribute
```
import unittest.mock
with unittest.mock.patch("something") as obj:
obj.f1()
```
The existing qualified only support name import, e.g.`import unittest`, and not support attribute import like `import unittest.mock` (when accessing qualified name of unitest.mock.patch, not result was returned.)
New unite test.
> [scope] add qualified name support for imported attribute

- libcst/metadata/expression_context_provider.py
- libcst/metadata/tests/test_expression_context_provider.py
add for loop support to ExpressionContextProvider.
CC @mvismonte 
New unit test.
> [metadata] add for loop support to ExpressionContextProvider

- libcst/_batched_visitor.py
- libcst/tests/test_batched_visitor.py
I messed up and forgot to hook up attribute visitors to batchable visitors when I implemented them. As a result, our internal lint framework can't use attribute visitors which makes some things impossible. Fix that here.
Added a new test that verifies visit behavior.
> Fix batchable visitor not calling attribute visitors

- libcst/_metadata_dependent.py
- libcst/metadata/tests/test_metadata_provider.py
> [metadata] fix typo and improve error message

- libcst/matchers/_visitors.py
> remove redundant code

- libcst/_nodes/base.py
- libcst/matchers/_matcher_base.py
- libcst/matchers/tests/test_extract.py
> remove unused import and run tox -e autofix

- libcst/codemod/__init__.py
- libcst/codemod/_cli.py
- libcst/codemod/_codemod.py
- libcst/codemod/_command.py
- libcst/codemod/_context.py
- libcst/codemod/_runner.py
- libcst/codemod/_testing.py
- libcst/codemod/_visitor.py
- libcst/codemod/commands/noop.py
- libcst/codemod/commands/tests/test_noop.py
- libcst/codemod/tests/test_codemod.py
- libcst/codemod/tests/test_metadata.py
- libcst/codemod/tests/test_runner.py
- libcst/codemod/visitors/__init__.py
- libcst/codemod/visitors/_add_imports.py
- libcst/codemod/visitors/_gather_imports.py
- libcst/codemod/visitors/tests/test_add_imports.py
- libcst/codemod/visitors/tests/test_gather_imports.py
- libcst/matchers/_visitors.py
- libcst/tool.py
This is the initial work needed to open-source the codemod framework. There is still a lot missing that I will be adding in a future PR: No ability to list/set up a repo, no config file format yet, lots of convenience features missing, etc. This code is mostly a direct export from Instagram's internal repo, with changes made to imports only. Hopefully splitting this way helps reviews.
tox, pyre.
> Intial Codemod Framework Open-Source

- libcst/codemod/commands/tests/test_convert_format_to_fstring.py
- libcst/tool.py
> apply new Black formatting

- requirements-dev.txt
> Upgrade Pyre to 0.0.36

- libcst/codemod/commands/strip_strings_from_types.py
> Black formatting

- CHANGELOG.md
- README.rst
- setup.py
> bump LibCST version to 0.2.6 and update README

- libcst/codemod/_cli.py
As it says on the tin! A simple runtime and estimated time left display is now available when running codemods. Thanks to @joshkehn for the implementation!
pyre, tox, ran noop codemod.
> Port runtime calculation by @joshkehn to open-source

- libcst/codemod/visitors/_add_imports.py
- libcst/codemod/visitors/tests/test_add_imports.py
This was updated by Ani over the break before I got a chance to cut instagram over to using open-source versions of everything. Port it over to open-source. This adds the ability to add an alias to an import when adding impots.
tox, pyre
> Port add import updates to open-source

- libcst/_nodes/base.py
- libcst/_parser/base_parser.py
- libcst/_parser/types/partials.py
- libcst/matchers/_visitors.py
Reuse CSTNodeT type var and clean up unused type var.
CI
> Reuse CSTNodeT type var and clean up unused type var

- libcst/tool.py
The way I coded this originally assumed that all codemods would exist in a single directory. This is already not the case inside Instagram, where we have multiple nested subdirectories of codemods. So, implement the ability to iterate over subdirectories. While I'm at it, deduplicate codemods that were re-exported from other modules such as tests by keeping only one version of a runnable codemod around.
tox, pyre, added some subdirectories and verified that codemods were listed, verified tests were not listed, verified duplicates were not listed.
> Support codemods in Subdirectories of configured modules.

- docs/source/codemods_tutorial.rst
Read through the tutorial after a few weeks and saw some typos. Fix them!
eyes
> Fix a few typos in docs

- libcst/codemod/_command.py
> Fix comment indentation

- libcst/matchers/_matcher_base.py
Add missing return value type to Callable and also reuse the typing to prevent duplication.
Pyre check.
> [typing] add missing return value type to Callable

- libcst/matchers/_visitors.py
> use transformer function (instead of visitor) in MatcherDecoratableTransformer

- libcst/codemod/commands/tests/test_convert_format_to_fstring.py
- libcst/codemod/commands/tests/test_unnecessary_format_string.py
- libcst/codemod/commands/unnecessary_format_string.py
> Fix some typos.

- libcst/metadata/type_inference_provider.py
- libcst/tool.py
> Clean up redundant code.

- docs/source/helpers.rst
- libcst/__init__.py
- libcst/_nodes/tests/test_assert.py
- libcst/_nodes/tests/test_global.py
- libcst/_nodes/tests/test_import.py
- libcst/_nodes/tests/test_nonlocal.py
- libcst/_nodes/tests/test_raise.py
- libcst/_nodes/tests/test_yield.py
- libcst/codemod/commands/add_pyre_directive.py
- libcst/codemod/commands/fix_pyre_directives.py
- libcst/codemod/visitors/_gather_imports.py
- libcst/helpers/__init__.py
- libcst/helpers/common.py
- libcst/helpers/expression.py
- libcst/helpers/tests/test_expression.py
- libcst/helpers/tests/test_module.py
- libcst/metadata/scope_provider.py
> expose all helpers in libcst.helpers for convenience

- libcst/tool.py
As it says on the tin. Allows wrapping scripts which provide CLI support to mandate a config file instead of using defaults.
Ran locally with and without config file and with and without env variable.
> Add environment variable to require config file before proceeding.

- libcst/tests/test_type_enforce.py
- requirements-dev.txt
Upgrading pyre to latest release to hopefully resolve issue with installation in CircleCI.
Upgraded and ran locally, tox, CI.
> Upgrade Pyre to 0.0.40

- libcst/metadata/tests/test_type_inference_provider.py
> [TypeInference] remove unused TODO comment

- docs/source/helpers.rst
> [doc] fix indentation

- libcst/codemod/commands/convert_format_to_fstring.py
- libcst/codemod/commands/strip_strings_from_types.py
This helper is available now, so use it where applicable.
pyre, existing tests.
> Use new SimpleString helper in a few codemods

- libcst/helpers/__init__.py
- libcst/helpers/expression.py
- libcst/helpers/tests/test_expression.py
add get_full_name_for_node_or_raise helpe. It's more convenient for some callsites.
unit test.
> add get_full_name_for_node_or_raise helper

- docs/source/helpers.rst
Add it to helpers.rst to present it in the doc.
> [doc] add get_full_name_for_node_or_raise

- libcst/_version.py
- libcst/codemod/visitors/_add_imports.py
- setup.py
> add copyright header

- README.rst
> Add pypi monthly download badge to README

- CHANGELOG.md
- libcst/_version.py
> [release] Bump LibCST to new release 0.3.3.

- README.rst
Follow up of https://github.com/Instagram/LibCST/pull/259
> Add `--preserve-pythonpath` option to `pyre check` in README.

- README.rst
> [docs] fix Pyre setup steps formatting in README

- README.rst
> [docs] improve readability per reader's feedback

- CHANGELOG.md
- libcst/_version.py
> [release] Bump LibCST to new release 0.3.4

- CHANGELOG.md
- libcst/_version.py
Bump to new version. Changes detailed in `CHANGELOG.md`
> Bump to version 0.3.7

- README.rst
- requirements-dev.txt
> Add tox to requirements-dev.txt and fixed a typo in README

- docs/source/best_practices.rst
as title.
Thanks @Kronuz reported this.
> [doc] use cst node in ensure_type in best practice doc

- CHANGELOG.md
- libcst/_version.py
> Bump to version 0.3.9

- libcst/metadata/tests/test_scope_provider.py
Wasn't actually testing the simple string annotation
Run tests
> Fix `test_annotation_access` test case.

- docs/source/conf.py
Add source code links to each class/function to make it very easy to view source code.
With this change, each class and function shows a green `source` link.
When click on a `source` link, it shows the source code.
> [docs] add source code links to each class/function

- README.rst
Update Codecov badge.
Use new https url.
.
> [README] update Codecov badge

- CHANGELOG.md
- libcst/_version.py
> bump version to 0.3.12

- CHANGELOG.md
- libcst/_version.py
Version bump to 0.3.15
Run existing tests
> Bump to version 0.3.15

- libcst/codemod/_cli.py
Instead of always launching the specified number of jobs or cpu_count, we should take into account how many files need to be processed and how many files are delivered at once to each process.
Note that this is similar to what fixit does, although they don't specify a chunk size.
> refactor: optimize number of parallel processes

- libcst/codemod/_cli.py
- libcst/tests/test_e2e.py
Fixes #447 
As I suspected, `git bisect` points at #402.
> Extra unused imports added in other files issue

- CHANGELOG.md
- libcst/_version.py
Bump version to 0.3.17
CI builds.
> Bump version to 0.3.17

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Instead of referencing `Name` nodes that are outside of the original CST, this PR makes `Access`es refer to the containing `BaseString` node (technically only `SimpleString | ConcatenatedString`).
Closes #381 
Added test cases.
TODO before merge:
> [scope-provider] tie accesses from string annotation to the string node

- .github/workflows/build.yml
1231231th time is the charm. Seriously, there must be a better way to do this
> [CI] fix python version in pypi upload step

- native/libcst/src/nodes/statement.rs
The compiler doesn't care, but it confused me for a few seconds when I saw this.
> Fix variable name in lambda

- libcst/_nodes/statement.py
- libcst/_nodes/tests/test_with.py
- libcst/_typed_visitor.py
- libcst/matchers/__init__.py
- native/libcst/src/nodes/statement.rs
- native/libcst/src/parser/grammar.rs
Creating an early draft PR for two reasons:
- I want to see CI results, I'm too lazy to run all the checks locally
- in case someone wants to look over the parts that are finished - at this point I've added parentheses to the python node, but not yet started any of the rust-side work.
> [WIP] Support Parenthesized With Statements

- README.rst
Our mission at Meta Open Source is to empower communities through open source, and we believe that it means building a welcoming and safe environment for all. As a part of this work, we are adding this banner in support for Ukraine during this crisis.
> docs: add social button in support of Ukraine

- requirements-dev.txt
Docs are broken because we're using some strange fork of sphinx that is now broken
> Pin jinja2 to a version that jimmy's fork of sphinx works with

- libcst/_parser/parso/pgen2/grammar_parser.py
- libcst/_parser/parso/python/token.py
- libcst/_parser/parso/utils.py
- libcst/codemod/commands/rename.py
- requirements-dev.txt
> Bump black to latest to address failures in Python 3.9/3.10

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
Add an `always_qualify_annotations` argument to `ApplyTypeAnnotationsVisitor` to apply imported type annotations qualified by their module names.
Added unit tests to `test_apply_type_annotations_visitor`.
> Add an argument to always qualify imported type annotations.

- docs/source/metadata.rst
Fix code example in metadata documentation.
Related issue: https://github.com/Instagram/LibCST/issues/449
Local manual test.
> Fix code example in metadata documentation.

- .github/workflows/ci.yml
> test using python 3.11 beta versions

- .github/dependabot.yml
Add dependabot configuration file for Python and Rust packages.
resolve: #715
> feat: dependabot config file

- .github/workflows/build.yml
- .github/workflows/ci.yml
Minor changes to build 3.11 wheels
closes #797 
No functional changes
> Python 3.11 wheels

- setup.py
Keep PyPI classifiers in sync with actually supported Python versions :)
> Add py3.11 classifier

- MANIFEST.in
- setup.py
See `pypi_upload` succeed on the sdist upload step. Also check the size of `hatch run python -m build --sdist`
> exclude native/target directory from sdist

- libcst/codemod/_cli.py
Otherwise lots of empty lines are printed.
> Print diff only when there is a change

- .github/workflows/ci.yml
ci: enable testing on windows + 3.11
> ci: enable testing on windows + 3.11

- .github/workflows/ci.yml
> ci: test with 3.12

- .github/workflows/ci.yml
- README.rst
- pyproject.toml
remove 3.8 support
This PR also starts using 3.12 properly in CI
> remove 3.8 support

- libcst/metadata/type_inference_provider.py
> remove mypy_extensions import

- CHANGELOG.md
- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst_derive/Cargo.toml
> Bump version to 1.4.0

- .github/workflows/ci.yml
- pyproject.toml
> include python 3.13 in build

- CHANGELOG.md
- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst_derive/Cargo.toml
> Bump version to 1.5.1

- README.rst
Missed this one in my previous PR
> bump 3.12 to 3.13 in readme

- .github/workflows/build.yml
- pyproject.toml
ci: move cibuildwheel config into pyproject.toml
> ci: move cibuildwheel config into pyproject.toml

- .github/workflows/build.yml
- pyproject.toml
ci: use native arm github runners
> ci: use native arm github runners

- .github/workflows/ci.yml
- libcst/codemod/_cli.py
- libcst/codemod/_dummy_pool.py
- native/libcst/src/py.rs
- pyproject.toml
ci: start building cp313t wheels
Closes #1242.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Instagram/LibCST/pull/1333).
* __->__ #1333
* #1295
> ci: start building cp313t wheels

- .github/workflows/ci.yml
> ci: stop using actions-rs actions

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/pypi_upload.yml
- native/Cargo.lock
- native/libcst/Cargo.toml
- pyproject.toml
This PR does two things:
1. makes sure the built wheels are exercised (by running a simple codemod on libcst sources themselves)
2. builds the wheels and runs the above tests on PRs to get early feedback
> ci: test built wheels

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
The old version generated an incorrect CST which
happened to work as long as you didn't do further processing.
I ran into this while attempting to apply multiple stub files to a single source file. The reproduction is finicky, but it generated some very wrong output when I hit it.
reproduction:
```python
import libcst as cst
from libcst import codemod
from libcst.codemod.visitors import ApplyTypeAnnotationsVisitor
py_source = """from module import B
M = B()
class Foo: pass
"""
pyi_source = """from module.submodule import B
M: B
class Foo: ...
"""
expected = """from module import B
import module.submodule
M: module.submodule.B = B()
class Foo: pass
"""
def merge(py_tree, pyi_tree):
context = codemod.CodemodContext()
ApplyTypeAnnotationsVisitor.store_stub_in_context(context, pyi_tree) …
```
> generate Attribute nodes when applying type annotations

- CHANGELOG.md
- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst_derive/Cargo.toml
> bump version to 1.8.5
