Instagram/LibCST

- docs/source/nodes.rst
- docs/source/visitors.rst
- libcst/_maybe_sentinel.py
- libcst/_removal_sentinel.py
- libcst/_visitors.py
These were referred to by other parts of the documentation, and provide
core parts of our functionality, so we should have explicit
documentation for them.
https://1371-200896124-gh.circle-artifacts.com/0/doc/nodes.html#maybe-sentinel
https://1371-200896124-gh.circle-artifacts.com/0/doc/visitors.html#libcst.RemovalSentinel
> Add docs for MaybeSentinel and RemovalSentinel

- libcst/metadata/dependent.py
Pyre doesn't handle inheriting from an ABC that implements __init__ properly right now so we're temporarily removing ABC from _MetadataDependent until Pyre is patched.
Run tox.
> Patch _MetadataDependent to not be an ABC until Pyre is fixed

- README.rst
- tox.ini
Apparently this works... don't know what I was doing last time I tried.
Ran tox and tox -e autofix.
> Add tox enviroment to run isort and black and update readme

- libcst/_batched_visitor.py
- libcst/_nodes/_base.py
- libcst/_nodes/_internal.py
- libcst/_nodes/_module.py
- libcst/_nodes/tests/base.py
- libcst/_nodes/tests/test_internal.py
- libcst/_nodes/tests/test_module.py
- libcst/metadata/_resolver.py
- libcst/metadata/base_provider.py
- libcst/metadata/position_provider.py
- libcst/metadata/tests/test_metadata_provider.py
- libcst/metadata/tests/test_position_provider.py
- libcst/metadata/wrapper.py
Removes compatibility hacks left in while porting code dependent on the old metadata API. This means when a node visits a visitor the metadata resolver will not be run and no deep clone will be performed. Metadata computation is now solely handled by the MetadataWrapper class.
Ran tox.
> Drop metadata compatibility

- README.rst
add link (as badge and text link) of notebook binder in README. Hope adding this can make the README easier to understand and more actionable.
Click on the link will open a window shows a editable notebook. (Note that it doesn't work on Chrome for me which only show the read-only notebook but it works on Safari)
https://mybinder.org/v2/gh/Instagram/LibCST/master?filepath=docs%2Fsource%2Fusage.ipynb
> add link of notebook binder in README

- .circleci/config.yml
- .gitignore
- requirements-dev.txt
- setup.py
- tox.ini
codecov is a code test coverage platform and it's free for open source.
https://codecov.io/#features
https://circleci.com/gh/Instagram/LibCST/1526?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://codecov.io/gh/Instagram/LibCST/src/cc244fc93327c615007ba1bdfee30f2309bbe08b/setup.py
> [CI] add test coverage run and codecov integration

- setup.py
Update minimum dependent package version in setup.py.
Find the version candidates from pypi https://pypi.org/project/typing-inspect/#history
Then try and test to see if all tests passed.
Run `python setup.py test`
```
Ran 1014 tests in 4.071s
OK
```
> update dependent package version in setup.py

- libcst/_nodes/_module.py
- libcst/_parser/_types/config.py
- libcst/_parser/_types/tests/test_config.py
This PR has two parts:
1. We now raise an exception if the user tries to parse the code as anything other than 3.7.
2. The documentation has more details and should now properly reflect reality.
Unit tests. Built and inspected the documentation.
https://1540-200896124-gh.circle-artifacts.com/0/doc/parser.html#libcst.PartialParserConfig
https://1540-200896124-gh.circle-artifacts.com/0/doc/nodes.html#module
> Update PartialParserConfig to more clearly reflect that we only support Python 3.7 (#32)

- docs/source/parser.rst
- libcst/_exceptions.py
- libcst/_parser/_base_parser.py
- libcst/_parser/_conversions/expression.py
- libcst/_parser/_conversions/params.py
- libcst/_parser/_conversions/statement.py
- libcst/_parser/_wrapped_tokenize.py
- libcst/_parser/tests/test_parse_errors.py
- libcst/_parser/tests/test_wrapped_tokenize.py
- libcst/tests/test_exceptions.py
`ParserSyntaxError` is a little too coupled to how pgen2 works (my fault), making some error messages bad and preventing us from using it everywhere we should.
A more detailed description of this problem is available in #24.
After refactoring `ParserSyntaxError`, this uses it in places where we should've been raising a `ParserSyntaxError`, but were raising an `Exception` instead.
Unit tests!
> Make ParserSyntaxError more generic and use it in more places

- libcst/_nodes/_statement.py
- libcst/_parser/_detect_config.py
- libcst/_parser/_entrypoints.py
- libcst/_parser/_whitespace_parser.py
- libcst/_parser/tests/test_detect_config.py
- libcst/tests/test_fuzz.py
This PR contains a series of diffs that address various bugs in LibCST found by Hypothesis. After this stack, at least locally, I can run the Hypothesis suite using `tox -e fuzz` with no errors. I'm pretty sure that fixing `parse_statement` to default to always using `\n` necessitates a way to grab a `PartialParserConfig` out of a parsed `Module`, but I didn't include that convenience attribute in this PR since it is somewhat separate.
`tox` as well as `tox -e fuzz`.
> Hypothesis Fixes

- libcst/_nodes/_module.py
- libcst/_nodes/tests/test_module.py
This is useful when you are using `parse_expression` or `parse_statement` to generate a tree from a source string that is meant to be later added to an existing module. It allows you to more easily configure both of these parser functions to output a tree which has the same defaults as the `Module` that you previously parsed out.
`tox` to run the new test and generate new docs. Also, verified using python REPL that desired behavior worked fine.
> Create a `config_for_parsing` property on `Module`.

- MANIFEST.in
- setup.py
LibCST is fully typed and mypy is the most popular type checker. 
More context in https://github.com/Instagram/LibCST/issues/57.
Based on https://python.org/dev/peps/pep-0561/ to add py.typed setting and update setup.py.
After installed the build package, mypy didn't complaint the missing import error.
```
jimmylai-mbp:LibCST jimmylai$ python setup.py sdist
Writing libcst-0.1.2/setup.cfg
Creating tar archive
removing 'libcst-0.1.2' (and everything under it)
jimmylai-mbp:LibCST jimmylai$ ls dist/
libcst-0.1.2.tar.gz
(mypy-libcst-env) jimmylai-mbp:mypy-libcst jimmylai$ cat a.py
import libcst
(mypy-libcst-env) jimmylai-mbp:mypy-libcst jimmylai$ mypy a.py
a.py:1: error: Cannot find module named 'libcst'
a.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports …
```
> support mypy using py.typed

- README.rst
- libcst/_nodes/tests/test_await.py
- libcst/_nodes/tests/test_for.py
- libcst/_nodes/tests/test_simple_comp.py
- libcst/_nodes/tests/test_with.py
- libcst/_parser/_conversions/expression.py
- libcst/_parser/_conversions/params.py
- libcst/_parser/_conversions/statement.py
- libcst/_parser/_conversions/terminals.py
- libcst/_parser/_detect_config.py
- libcst/_parser/_entrypoints.py
- libcst/_parser/_grammar.py
- libcst/_parser/_parso/_python/_token.py
- libcst/_parser/_parso/_python/_tokenize.py
- libcst/_parser/_production_decorator.py
- libcst/_parser/_python_parser.py
- libcst/_parser/_types/config.py
- libcst/_parser/_types/production.py
- libcst/_parser/_types/tests/test_config.py
- libcst/_parser/tests/test_detect_config.py
- libcst/_parser/tests/test_version_compare.py
- libcst/_parser/tests/test_wrapped_tokenize.py
This PR adds support for parsing multiple versions of Python. Specifically, it adds support for 3.6, which exercises the need for versioning on grammar production decorators as well as a different tokenizer. All of the plumbing to make this happen based on the python version string in `PartialParserConfig` is included in this PR. It should be possible to add support for older grammars down to 2.7 and up through 3.9 after this PR lands.
Added several tests for the 3.6 tokenizer, and made sure to add some tests for 3.7/3.8 to verify that the behavior did not leak. Updated several tests for the parser/generator code to work with 3.6-style async/await behavior, thus exercising our ability to parse 3.6 code.
> Multiversion Support

- docs/source/metadata_tutorial.ipynb
- Added the `None` type to the `__init__` method in the metadata tutorial
https://libcst.readthedocs.io/en/latest/metadata_tutorial.html#Providing-Metadata
> Add type to init method in tutorial

- CHANGELOG.md
- setup.py
As it says on the tin! Bump the version so I can make a new release.
Compared to ast bump at https://github.com/Instagram/LibCST/commit/38d220d2247c389ef2de30f35b5e4bb56061216b
> Bump version to 0.1.3.

- LICENSE
- README.rst
Reproduce copyright headers in files that were forked from repositories other than LibCST in the LICENSE file. Add a copy of the PSF license to license file. Add a link to Apache 2.0 license in the license file. Add an acknowledgements section. Add a future section.
Pushed branch, looked at the rendered readme and license files.
> Clarify license

- libcst/metadata/__init__.py
- libcst/metadata/tests/test_base_provider.py
- libcst/metadata/tests/test_expression_context_provider.py
- libcst/metadata/tests/test_metadata_provider.py
- libcst/metadata/tests/test_parent_node_provider.py
- libcst/metadata/tests/test_position_provider.py
- libcst/metadata/tests/test_scope_provider.py
Consolidate metadata imports. Metadata users should just import needed metadata objects from `libcst.metadata` without remember submodule in libcst.metadata..
> consolidate metadata imports

- docs/source/index.rst
- docs/source/matchers.rst
- docs/source/matchers_tutorial.ipynb
- docs/source/nodes.rst
- docs/source/visitors.rst
- libcst/_nodes/base.py
- libcst/_nodes/tests/test_removal_behavior.py
- libcst/_removal_sentinel.py
- libcst/_visitors.py
- libcst/codegen/gen_matcher_classes.py
- libcst/matchers/_decorators.py
- libcst/matchers/_matcher_base.py
- libcst/matchers/_visitors.py
- libcst/matchers/tests/test_decorators.py
- libcst/matchers/tests/test_matchers.py
- libcst/matchers/tests/test_visitors.py
- libcst/metadata/scope_provider.py
As promised, this is the documentation for matchers. Included in this is documentation on how to use matchers, as well as a tutorial to help get started and show off various concepts. Also, I was naughty and snuck in two things: 1) A fix to a warning when generating docs. 2) Fixed matchers being incapable of combining @call and @visit/@leave even though it was designed to do so. Those are at least kept in separate commits.
tox, also look at the generated docs by CI (the pages are far too big to screenshot here).
> Matchers Documentation

- docs/source/index.rst
As we add more doc pages, we need to categorize pages better for readability.
Organize document menu as three parts: introduction, tutorial and reference.
Before
After
> Organize document menu as three parts: introduction, tutorial and reference

- libcst/_nodes/base.py
- libcst/tests/test_deep_replace.py
Implement a `deep_replace()` helper method on CSTNode. This allows you to replace an instance of `old_node` by identity with `new_node`. This helper isn't extremely useful on its own, but coupled with a planned `find()` method in matchers this will allow for find and replace on arbitrary parts of the tree.
Added a new test to verify functionality.
> Implement deep_replace helper on CSTNode.

- docs/source/visitors.rst
- libcst/__init__.py
- libcst/_nodes/base.py
- libcst/_nodes/tests/test_removal_behavior.py
- libcst/_removal_sentinel.py
- libcst/_visitors.py
- libcst/codegen/gen_matcher_classes.py
- libcst/tests/test_deep_replace.py
We've gotten a few comments that RemovalSentinel is a bit difficult to use. Its not that intuitive to return RemovalSentinel.REMOVE. We already have helper methods on `CSTNode` which return new values (`deep_clone`, `with_changes`) so we have precedent here for adding another. Add a `deep_remove` onto CSTNode that can be called similar to the other modifying calls, and identically to `deep_replace` which was newly added. Add a `RemoveFromParent()` helper method that constructs a `RemovalSentinel.REMOVE` and refer to that as the default in documentation. Hopefully this helps the ergonomics of removing nodes a bit.
tox, look at generated docs.
> Add deep_remove and RemoveFromParent() to LibCST.

- docs/source/index.rst
- docs/source/metadata.rst
- docs/source/scope_tutorial.ipynb
- libcst/metadata/__init__.py
- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Add `Scope.assignments` returns a `Assignments` which supports `__contains__`, `__iter__`, `__getitem__`.
Add `Scope.accesses` returns a`Accesses` which supports `__contains__`, `__iter__`, `__getitem__`.
Add `Access.referents` and `Assignment.references` to link an assignment to an access and vice versa.
Add scope analysis tutorial to demonstrate use cases: find unused import and undefined access; autofix unused import.
https://2960-200896124-gh.circle-artifacts.com/0/doc/index.html
unit test.
> Add Assignments and Accesses to Scope Analysis

- libcst/metadata/scope_provider.py
Previously the docstring was missing and it's not clear what's inside QualifiedName. Added the docstring.
Before
After
> [doc] add docstring to QualifiedName

- libcst/matchers/tests/test_decorators.py
- libcst/matchers/tests/test_matchers.py
- libcst/matchers/tests/test_visitors.py
As it says on the tin!
Grepped for `ONCALL`, deleted instances.
> Clean up on-call specification leftover from open-sourcing

- libcst/_metadata_dependent.py
- libcst/metadata/base_provider.py
Because we'd consider `BaseMetadataProvider[int]` to be a subtype of
`BaseMetadataProvider[object]`, it should be covariant over its
typevar, rather than invariant.
This isn't entirely correct because we have a mutable data structure
(`_computed`) that depends on the typevar, and pyre points this out
(though with a really confusing error message). However, it's not
correct to say that `BaseMetadataProvider` is invariant either, so I
think this is the lesser evil.
I don't think it's practical to redesign this API to avoid the variance
issue, so I'm ignoring the new type error that results from this change.
I think this may resolve some of the issues we've seen internally with
D17820032.
```
pyre check
```
> Make `BaseMetadataProvider[T]` covariant over `T`

- libcst/codegen/gen_matcher_classes.py
- libcst/matchers/__init__.py
- libcst/matchers/_matcher_base.py
- libcst/matchers/tests/test_decorators.py
During the discussion on the RFC for matchers + metadata we ran into issues with matchers as they're currently defined. This PR shores up potential immutability issues with special matchers and defines an explicit `__hash__` and `__eq__` for matchers (both concrete and special). Given the fact that dataclasses become fairly useless if you also override their `__init__`, I opted to manually provide immutability via properties on special matchers.
Wrote a new test that failed before these fixes. Pyre and tox for normal stuff.
> Immutability and Hash/Equality for Matchers

- libcst/_typed_visitor.py
- libcst/codegen/gen_matcher_classes.py
- libcst/codegen/generate.py
- libcst/codegen/tests/test_codegen_clean.py
- libcst/codegen/transforms.py
I noticed that the typed visitors codegen was creating messy types such as `Union[SingleType]`. We have a clean-up for `Union[SingleType]` snuck into `gen_matcher_classes`. So, lets remove that snuck-in clean-up from `gen_matcher_classes` and apply it globally to all codegen. This makes its purpose a lot more obvious, while helping decouple necessary codegen from prettifying/simplifying transforms. It also cleans up typed visitors, so that's a bonus.
tox
> Generalize codegen cleanup step and apply it to all codegen

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_qualified_name_provider.py
Previously we don't handle ComprehensionScope in QualifiedName and just raised exception because comprehension wasn't defined in PEP-3155 https://www.python.org/dev/peps/pep-3155/.
In real-world, it made the QualifiedName metadata hard to use because it's common to define new variable in comprehension scope.
In this PR, we proposed to use const str `<comprehension>` to represent a comprehension scope in qualified name because there is no name associated with a comprehension (unlike function and class scope).
```
class C:
def fn(self) -> None:
[[k for k in i] for i in [j for j in range(10)]]
```
> Handle ComprehensionScope in QualifiedName

- libcst/matchers/tests/test_matchers.py
As discussed offline, use tuple for Sequence may cause confusion when nested with many other parentheses.
This PR was generated using those two transformers.
```
module = cst.parse_module(src)
class CallTransformer(cst.CSTTransformer):
def leave_Call(self, o, u):
if m.matches(
u,
m.Call(
func=m.Attribute(
value=m.Name("cst") | m.Name("m"), attr=m.Name("Call")
),
args=[m.AtLeastN(n=2)],
),
):
return u.with_changes(
args=[
cst.Arg(keyword=cst.Name("func"), value=u.args[0].value),
cst.Arg(keyword=cst.Name("args"), value=u.args[1].value),
]
)
return u
class CSTImportTransformer(cst.CSTTransformer):
def leave_Attribute(self, o, u):
if m.matches(u, m.Attribute(value=m.Name("libcst"))):
return u.with_changes(value=cst.Name("cst"))
return u
```
> Use import libcst as cst and explicit keyword arg for consistency and readability

- docs/source/metadata.rst
Explaining the implementation details of scopes to someone unfamiliar
with compilers can be tricky. Hopefully this helps.
- Rephrased the definition of a scope to be more applicable to Python
(remove references to "blocks"), and made it use an example for
(hopefully) better clarity.
- New scopes are also created for comprehensions.
- Set a fixed width (400px) for the scope diagram, since it was too
large before.
- Tweaked some tenses.
- Add a final call to action: "LibCST allows you to inspect these
scopes"
> Tweak wording/formatting of the scope provider intro

- docs/source/metadata.rst
- libcst/_nodes/internal.py
- libcst/_nodes/module.py
- libcst/_nodes/tests/base.py
- libcst/_nodes/tests/test_internal.py
- libcst/_nodes/tests/test_module.py
- libcst/metadata/__init__.py
- libcst/metadata/position_provider.py
- libcst/metadata/tests/test_position_provider.py
I discussed the high-level idea here with @DragonMinded a few months
ago, but this isn't set in stone. If people have better ideas for names,
I'd love to hear it.
- SyntacticPositionProvider is deprecated. The new name is
PositionProvider.
- BasicPositionProvider is deprecated. The new name is
WhitespaceInclusivePositionProvider.
- Documentation is updated to better explain these renamed providers and
how to use them.
The prefixes "Syntactic" and "Basic" were pretty bad because they're
just concepts that we made up for LibCST.
The idea for the new names is that most users will want the
SyntacticPositionProvider, and so we should name things so that the user
will naturally gravitate towards the correct choice.
There's some argument that we shouldn't even bother exposing …
> Rename position provider classes

- libcst/_nodes/base.py
- libcst/_nodes/tests/test_assign.py
- libcst/_nodes/tests/test_subscript.py
- libcst/_parser/conversions/expression.py
- libcst/codegen/gen_matcher_classes.py
- libcst/codegen/transforms.py
- libcst/tests/test_deprecate_extslice.py
This makes sure we always wrap elements in a SubscriptElement, even when there
is only one element. This makes things more regular while still being backwards
compatible with existing creation. The meat of this is in two halves, which can't
be split due to not wanting to break the build between commits. The first half
is just the changes to the parser and updates to tests. This includes a test to
be sure we can still render code that uses old construction types. The second half
is changes to codegen which made assumptions about `Subscript` and demonstrates
the need to make this change in the first place. This includes a fix to
`CSTNode.with_deep_changes` type to make it more correct and also more usable in
transforms without additional type assertions.
Existing tests, added another …
> Remove parsing Subscript slice directly into Index/Slice

- docs/source/metadata_tutorial.ipynb
I missed this in #114 when renaming `SyntacticPositionProvider` to
`PositionProvider` because it's a different file extension and I was
only grepping for rst and py files.
```
tox -e docs
```
> Update tutorial to use renamed PositionProvider

- libcst/_parser/detect_config.py
- libcst/_parser/tests/test_detect_config.py
If you have such a program like "pass\\\n", this is technically a program without a trailing newline, since line continuations are defined as being a `\` followed by a newline. We were misdetecting this as having a trailing newline, thus making it impossible to parse the continuation. Add some tests to verify this behavior and then fix the problem.
Note that this was found via hypothesis.
tox
> Fix trailing newline detection around continuation

- libcst/tests/test_fuzz.py
- tox.ini
Let's split from just fuzzing on the default python to having a separate fuzzer for each version of python we support. This should help us catch any issues should they arise in differences with grammars across releases. Right now we're fuzz-clean as well, so I also bumped up the thresholds to stress test LibCST more. I anticipate that this will be useful when we begin work on 3.8 support.
`tox -e fuzz36 ; tox -e fuzz37` which complete in about 90 seconds each.
> More explicit fuzz testing environments

- libcst/_nodes/base.py
- libcst/_nodes/internal.py
- libcst/metadata/position_provider.py
- libcst/metadata/tests/test_position_provider.py
I need to do some additional work on visit/leave to make codegen
re-entrant, so this makes it more generic.
This should have an additional small positive effect of creating less
throwaway objects when we're doing codegen without position calculation.
pyre/unit tests/lint
> Make the codegen enter/leave tracking more generic

- docs/source/experimental.rst
- docs/source/index.rst
- libcst/_nodes/internal.py
- libcst/_nodes/module.py
- libcst/_nodes/tests/test_namedexpr.py
- libcst/metadata/__init__.py
- libcst/metadata/position_provider.py
- libcst/metadata/reentrant_codegen.py
- libcst/metadata/tests/test_position_provider.py
- libcst/metadata/tests/test_reentrant_codegen.py
**Context:** This is an experimental performance optimization that we're
hoping to use for our internal linter at Instagram. I added some
documentation, but it's unsupported, and isn't very user-friendly.
This adds `ExperimentalReentrantCodegenProvider`, which tracks the
codegen's internal state (indentation level, character offsets,
encoding, etc.) and for each statement, it stores a `CodegenPartial`
object.
The `CodegenPartial` object has enough information about the previous
codegen pass to run the codegen on part of a tree and patch the result
back into the original module's string.
In cases where we need to generate a bunch of small independent patches
for the same file (and we can't just generate a new tree with each patch
applied), this *should* be a faster alternative.
I don't …
> Add a reentrant (incremental) codegen API

- requirements-dev.txt
We don't need to worry about formatting changes since we already paid the cost
in b3253de9b8b08bd9df00193a749e88e5a19d6d95. So, now that there's a new 3.8-compatible
Black, lets use it!
tox
> Use official release of Black now that it is out.

- docs/source/metadata.rst
- libcst/metadata/tests/test_metadata_wrapper.py
- libcst/metadata/wrapper.py
In certain cases (e.g. inside Instagram's lint framework) we know that
our tree originates from the parser, so we know that there shouldn't be
any duplicate nodes in our tree.
MetadataWrapper exists to copy the tree ensuring that there's no
duplicate nodes.
This diff provides an escape hatch on MetadataWrapper that allows us to
save a little time and avoid a copy when we know that it's safe to skip
the copy.
As part of this, I ran into some issues with `InitVar` and pyre, so I
removed `@dataclass` from the class. This means that this is techincally
a breaking change if someone depended on the `MetadataWrapper` being an
actual dataclass, but I think this is unlikely. I implemented `__repr__`
and added tests for hashing/equality behavior.
Unit tests!
> Add an unsafe_skip_copy option to MetadataWrapper

- docs/source/matchers.rst
- libcst/codegen/gen_matcher_classes.py
- libcst/matchers/__init__.py
- libcst/matchers/_matcher_base.py
- libcst/matchers/_visitors.py
- libcst/matchers/tests/test_findall.py
Findall does what you expect given a matcher and a tree: It returns all nodes
that exist in that tree which match the given matcher. For convenience, findall
works with regular LibCST trees as well as MetadataWrappers. It is also provided
as a helper method on the matcher transforms.
Note that this does not return an iterator. I based this decision on the fact that we
don't currently have a way to use visitors under the hood to create an iterator. If I
were to implement this myself, I would effectively be reinventing traversal of trees.
I don't think this is that big of a deal. If we need an efficient way to find the first
occurance of a match in a tree, I can implement `find` which bails early and document
it as such. For now, I don't want to overcomplicate the API, so I will wait until …
> Implement `findall` in matcher API.

- docs/source/matchers.rst
- libcst/codegen/gen_matcher_classes.py
- libcst/matchers/__init__.py
- libcst/matchers/_matcher_base.py
- libcst/matchers/tests/test_matchers_with_metadata.py
This is especially helpful for checking qualified names of nodes against one item
or a list of items that you wish to match against. I chose to create a new matcher
instead of widening the type of `MatchMetadata` to take in either a value or
a callable. I was originally going to do the former, but having a MatchIfTrue
and a MatchMetadataIfTrue felt more orthogonal and became easier to explain than
a single MatchIfTrue that could take two types of values.
tox
> Implement a `MatchMetadataIfTrue` matcher

- docs/source/scope_tutorial.ipynb
This PR fixes a typo in the `docs/source/scope_tutorial.ipynb` file.
> Fix typo in "scope_tutorial.ipynb" file.

- docs/source/why_libcst.rst
This PR fixes a typo in the `docs/source/why_libcst.rst` file.
> Fix typo in "why_libcst.rst" file.

- CHANGELOG.md
- setup.py
Its time for a new release. Update the version and changelog.
Ran tox.
> Bump LibCST to 0.2.3.

- libcst/codegen/gen_matcher_classes.py
- libcst/matchers/__init__.py
Basically, I screwed up when I did the codegen refactor and didn't widen types for sequences properly. This re-allows sequence wildcards to be used as entries in a sequence, and fixes the `MatchIfTrue` stanza for sequence types.
Pyre, tox, compare to internal codemods that require these widened types.
> Fix not widening matcher sequence types inside unions

- CHANGELOG.md
- setup.py
As it says on the tin! Types are fixed so its time to release again.
tox
> Bump LibCST to 0.2.4.

- libcst/matchers/_matcher_base.py
These checks are well-intentioned, but unfortunately make construction of a OneOf/AllOf from a sequence expansion a pain in the ass. So, drop them. The code already does the right thing, this was just providing helpful messages.
All existing tests. Eyes.
> Remove length restrictions for AllOf/OneOf

- libcst/matchers/_visitors.py
- libcst/matchers/tests/test_visitors.py
I guess even on newer Python versions, pickling exceptions still doesn't work right. Fix that here.
Wrote a new test to verify pickleability!
> Make matcher type hint exception pickleable

- docs/source/matchers.rst
- libcst/codegen/gen_matcher_classes.py
- libcst/matchers/__init__.py
- libcst/matchers/_matcher_base.py
- libcst/matchers/_visitors.py
- libcst/matchers/tests/test_findall.py
This is equivalent to calling `findall` on a node, and then calling `extract` with the same
matcher on each of the returned nodes from `findall`.
tox, added tests. This is a refactor of `findall` so I expect most edge cases to be covered already. I only tested the basic cases as a result.
> Implement an `extractall` function

- libcst/_nodes/expression.py
- libcst/_nodes/tests/test_funcdef.py
- libcst/_nodes/tests/test_lambda.py
- libcst/_parser/conversions/params.py
- libcst/metadata/tests/test_scope_provider.py
Deprecate "default_params". All uses of this outside of the this repo inside Instagram just combine "params" and "default_params" which says that the distinction was not necessary. This also stops us from supporting `/` for positional only parameters in 3.8. This diff deprecates this by allowing "default_params" in construction, but never parses to them. Given that complete removal of "default_params" is a breaking change, we must wait until at least 0.3.0 to remove it and add support for `/`. At that point, we can bump 3.8 support to official.
This is necessary but not sufficient for #122 
Updated existing tests, pyre.
> Deprecate "default_params" on Parameters

- docs/source/matchers.rst
- libcst/codegen/gen_matcher_classes.py
- libcst/matchers/__init__.py
- libcst/matchers/_matcher_base.py
- libcst/matchers/_visitors.py
- libcst/matchers/tests/test_replace.py
This takes a tree, a matcher, and a replacement, replacing all nodes in the tree which match the shape of the matcher with the replacement. It works similar to `findall` or `extractall`, but runs similar to a transform.
wrote some new tests
> Implement a `replace` function

- CHANGELOG.md
- README.rst
- setup.py
As it says on the tin. We have a lot of bugfixes to get out.
tox, pyre
> Bump LibCST to 0.2.5.

- libcst/_typed_visitor_base.py
- libcst/matchers/tests/test_decorators.py
- libcst/tests/test_batched_visitor.py
- libcst/tests/test_deprecate_extslice.py
- libcst/tests/test_visitor.py
fix #161 by following decorator type preservation example code in mypy docs: https://mypy.readthedocs.io/en/latest/generics.html#declaring-decorators
will consult with libcst folks on type tests
> Fix mark_no_op decorator type preservation on mypy

- docs/source/codemods.rst
- docs/source/codemods_tutorial.rst
- docs/source/index.rst
- docs/source/scope_tutorial.ipynb
- docs/source/tutorial.ipynb
- libcst/codemod/_cli.py
- libcst/codemod/_codemod.py
- libcst/codemod/_command.py
- libcst/codemod/_context.py
- libcst/codemod/_runner.py
- libcst/codemod/_visitor.py
- libcst/codemod/visitors/_add_imports.py
- libcst/codemod/visitors/_gather_imports.py
- libcst/helpers/module.py
Add documentation for ``libcst.tool``, and ``libcst.codemod`` directory. This includes full documentation for Codemods, CodemodCommands, the CLI, helper functions and the current set of transforms in our transform library and helpers.
`tox -e docs`, this is far too much documentation to screenshot so please look at the generated docs in the CI artifacts.
> Add documentation for libcst.codemod and friends.

- libcst/_parser/conversions/expression.py
- libcst/_position.py
- libcst/_type_enforce.py
- libcst/codegen/gather.py
- libcst/codemod/commands/tests/test_convert_format_to_fstring.py
- libcst/tool.py
- requirements-dev.txt
Upgrade pyre-check version. Pyre has new version 0.0.33, upgrading to it to test type checking.
CC @shannonzhu
We expect pyre-check to have a newer version later today. Will bump the version to 0.0.34 when the new version is available.
Existing type checking.
> Upgrade pyre-check version

- libcst/codemod/commands/strip_strings_from_types.py
- libcst/codemod/commands/tests/test_strip_strings_from_types.py
As it says on the tin. We don't have a good example of this in open-source codemods. Also, the codemod itself is more incorrect without than with, so lets fix that by adding this!
Existing tests (which include literal support tests) and a few new ones to show off that this does indeed capture what we want it to.
> Use qualified name scope in string replacement codemod

- libcst/codemod/_cli.py
- libcst/codemod/_codemod.py
- libcst/codemod/_runner.py
- libcst/codemod/_testing.py
- libcst/codemod/commands/tests/test_convert_format_to_fstring.py
- libcst/tool.py
Allow python version overrides for various libcst.codemod transformation utilities and plumb that out to the command-line. As a bonus, this gets rid of a render/parse loop for multi-pass codemods since we are 100% sure now that metadata calculation results in a unique tree.
tox, pyre
> Version override in libcst.tool

- libcst/codemod/commands/strip_strings_from_types.py
- libcst/tests/pyre/simple_class.json
- libcst/tests/pyre/simple_class.py
- libcst/tests/test_pyre_integration.py
- requirements-dev.txt
add test suite for pyre regression test.
Explicitly not to add `pyre-strict` to test files to make sure pyre can infer some of the types smartly.
Missing or wrong inferred typing issues are commented.
CC @shannonzhu
Run the command to generate pyre output in test suite directory tests/pyre: `python libcst/tests/test_pyre_integration.py`
Tried to run the script in CI to automatically verify the generated file is up to date but pyre query depends on watchman and it's not straightforward to install watchman in CI environment.
This attempt filed: https://app.circleci.com/jobs/github/Instagram/LibCST/4633/parallel-runs/0/steps/0-104
Pyre 0.0.36 didn't work well. Upgrade to 0.0.38 resolved a couple type coverage and accuracy issues.
Issue: we should try avoiding the test py file was formatted …
> add test suite for pyre regression test

- README.rst
- libcst/tests/test_pyre_integration.py
as title.
https://libcst.readthedocs.io/en/latest/usage.html is renamed and it's 404 now.
> Remove unused parentheses and fix broken usage link in README

- libcst/metadata/__init__.py
- libcst/metadata/tests/test_type_inference_provider.py
- libcst/metadata/type_inference_provider.py
- libcst/tests/test_pyre_integration.py
Type inference metadata surface type annotation data (str) provided by pyre query on Name, Attribute and Call nodes.
Sometimes type annotation is not available and the available type annotation may not be useful. We'll continue to work with Pyre team to increase the coverage and accuracy.
This is the first step, later on, we may be able to use Scope Analysis to simplify the type and it'll be useful if we can provide the Assignment/Scope info.
Unit tests.
> Type inference metadata

- .circleci/config.yml
- libcst/tests/test_pyre_integration.py
Run pyre codegen in CI to make sure Pyre codegen changes are always reviewed and committed proactively.
Pyre query depends on Pyre server. We start Pyre server in the codegen script before querying.
CI job run.
When no changes are generated. Pyre job passed. https://app.circleci.com/jobs/github/Instagram/LibCST/4887/parallel-runs/0/steps/0-103
When changes are generated. Pyre job failed.
https://app.circleci.com/jobs/github/Instagram/LibCST/4900/parallel-runs/0/steps/0-103
> run pyre codegen in CI

- libcst/metadata/tests/test_type_inference_provider.py
- libcst/tests/pyre/simple_class.json
- libcst/tests/pyre/simple_class.py
- libcst/tests/test_pyre_integration.py
Based on feedback in https://github.com/Instagram/LibCST/pull/172/files, change to use strict mode for better test cases.
Unit tests.
> Use Pyre strict mode in Pyre test suite

- CHANGELOG.md
- README.rst
- setup.py
Minor version bump to include a few things that were modified over the break. This brings open-source up to date with the internal version of libcst.codemod, which will be going away soon.
tox, pyre
> Bump LibCST to 0.2.7

- docs/source/codemods.rst
- docs/source/metadata.rst
- libcst/codemod/_testing.py
- libcst/metadata/position_provider.py
Add docs for `CodemodTest`, so that people know how to test their codemods. Unfortunately it looks like sphinx cannot both include inherited members AND specify an explicit list of members, so in order to get documentation to show up right for this class I had to explicitly opt out all of `Unittest`. What a pain. However, it works, and the documentation rendering properly is more important than the code looking nice.
I also fixed the warnings that crept into the docs process during this PR.
tox -e docs, verified no errors, verified docs rendered right.
> Add docs for CodemodTest

- docs/source/scope_tutorial.ipynb
- libcst/codemod/tests/test_metadata.py
- libcst/matchers/_matcher_base.py
- libcst/matchers/tests/test_extract.py
- libcst/matchers/tests/test_matchers_with_metadata.py
- libcst/metadata/__init__.py
- libcst/metadata/position_provider.py
As it says on the tin! Prepare for LibCST 0.3.0 release by removing these deprecated objects.
pyre, tox
> Remove deprecated position provider objects

- libcst/__init__.py
- libcst/matchers/tests/test_extract.py
- libcst/matchers/tests/test_matchers_with_metadata.py
- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Remove deprecated imports and attributes in libcst.metadata in preparation of LibCST 0.3.0.
tox, pyre
> Remove deprecated attributes and objects in metadata

- libcst/testing/utils.py
- libcst/tests/pyre/simple_class.json
- libcst/tool.py
- requirements-dev.txt
Upgrade Pyre to 0.0.39. It removed the redundant file path from pyre query which make the output more compact and performant.
Pyre check.
> Upgrade Pyre to 0.0.39

- libcst/tool.py
As it says on the tin. This is especially helpful for manually specifying a ton of files to codemod since you might otherwise hit the linux command length limit.
tox, pyre, ran locally with a file that contained args
> Support reading arguments from file

- libcst/codemod/_testing.py
Apply make_fixture_data() to codemod output.
This is useful for codemod creates empty leading or trailing lines. Without this change, it's hard to test those cases.
Existing tests.
> Apply make_fixture_data() to codemod output

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_qualified_name_provider.py
Those patterns are used very often currently and this helper makes it simpler to users.
`any(qn.name == target_name for qn in self.get_metadata(QualifiedNameProvider, node, set()))`
`any(qn == target_qualified_name for qn in self.get_metadata(QualifiedNameProvider, node, set()))`
Some user may do it with for loop + if condition which makes it more complex.
With the new helper: `QualifiedNameProvider.has_name(visitor, node, "target")`
Unit test.
> [helper] QualifiedNameProvider.has_name

- libcst/tool.py
I ran into this when testing f-strings in 3.8, where I wanted to parse and print trees on a newer python than my system python. We already have a version override for `libcst.tool codemod`, so there is no reason not to support it as well for `libcst.tool print`. Copied wholesale over from the `codemod` command so it works identically.
Tested with named expr parsing using system python 3.7.
> Implement a --python-version override flag to "libcst.tool print".

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
In the use case like rename a variable, we'll want to track the reference even it's in a `del` context.
Unit test.
> [scope] add support for tracking reference in del expression context

- README.rst
- docs/source/helpers.rst
- libcst/_nodes/tests/test_funcdef.py
- libcst/_nodes/tests/test_lambda.py
- libcst/_parser/conversions/params.py
- libcst/_parser/grammar.py
- setup.py
Implement parsing of posonly param indicator ('/'). This brings us to full 3.8 compatibility.
added a decent amount of new tests, pyre, existing tests, also ran the fuzzers for 3.6,3.7 and 3.8.
> Parse posonly param indicator in functions/lambdas.

- CHANGELOG.md
- setup.py
As it says on the tin.
tox, pyre, imported a preview release into internal code and verified things worked.
> Bump LibCST to new release 0.3.0.

- libcst/_nodes/expression.py
We parse this correctly, but the documentation is wrong. Update it to match Python 3 actual behavior.
Opened python in console, verified you could not have spacing inside or after conversion or format_spec.
> Clarify documentation about f-string spacing

- libcst/_nodes/expression.py
- libcst/_nodes/tests/test_atom.py
- libcst/codemod/commands/convert_format_to_fstring.py
- libcst/codemod/commands/tests/test_convert_format_to_fstring.py
We have a helper in one of our codemods that should really be universally available. So, move the relevant bits into libcst core, remove them from the codemod, update the codemod to use the new behavior and update the tests accordingly.
tox, pyre, new tests
> Refactor string split helper method into core attributes.

- libcst/tool.py
If a module is naughty and does work on import, and that work crashes for some reason, we don't want to take down the list command. So, be more permissive in list command exceptions swallowed.
Tested internally, also existing tests, pyre, tox.
> Fix list behavior

- libcst/_nodes/expression.py
- libcst/helpers/tests/test_expression.py
`literal_eval(node.value)` has been used often to get the evaluated string value from a `SimpleString`.
It requires `from ast import literal`. This helper is a shortcut to make it easier.
unit test.
> add SimpleString.evaluated_value

- docs/source/best_practices.rst
- docs/source/helpers.rst
- libcst/helpers/__init__.py
- libcst/helpers/_template.py
- libcst/helpers/tests/test_template.py
Implement basic templated statement/expression/module parsing. This has some corner cases that we do not currently handle, but those will come in a later commit. For example, if you try to substitute a `Parameters` node, it will currently fail. There are checks to let you know that it is not supported, but additional smarts will have to be added to make this work in the future.
Added some basic tests, pyre, existing tests.
> Implement basic templated statement/expression/module parsing

- libcst/codemod/_cli.py
- libcst/codemod/_codemod.py
- libcst/codemod/_context.py
- libcst/metadata/full_repo_manager.py
- libcst/tool.py
- setup.py
This makes it such that when you write a codemod, you need only to depend on the `TypeInferenceProvider` in your codemod, the way you would a non-full-repo metadata provider. `libcst.tool` will handle the rest, including cache computation and passing values around.
pyre, existing tests, also installed libcst into a new virtualenv, initialized `libcst.tool` and `pyre` in a new directory, added a file with types and added a codemod that printed the type of each name it encountered. Types were printed as expected.
> Full Repo Metadata support in Codemod Tool

- libcst/codemod/commands/convert_precent_format_to_fstring.py
- libcst/codemod/commands/tests/test_convert_percent_format_to_fstring.py
Port the codemod from lint.
With the prefix, quote, raw_value, evalurated_value helpers provided by SimpleString. The implementation became much simpler now.
Questions to be discussed: (can be addressed by follow up PRs)
- can we rename VisitorBasedCodemodCommand as TransformerBasedCodemodCommand? Visitor implies the ready only visitor pattern and Transformer represents the mutable leave_ API.
- can we consolidate the interface provided by lint framework and codemod framework? That way we can easily convert a codemod as a lint fixer very easily. Currently the conversion wasn't trivial and can be error-prone.
- add a msg as third parameter to assertCodemod? The standard test assert helpers (e.g. assertEqual) takes a msg parameter which can be a useful message when test failed. It's …
> [codemod] add ConvertPercentFormatStringCommand

- libcst/_nodes/expression.py
- libcst/codegen/gen_matcher_classes.py
- libcst/codegen/transforms.py
- libcst/helpers/common.py
- libcst/helpers/tests/test_expression.py
Extend the support for `evaluated_value` from just strings to numbers as well. Follow up with a few tweaks to code that used `literal_eval` and swap it over to using the calculated properties. Update the docs to encourage using the properties instead of `literal_eval` as well.
new and existing tests, pyre, tox
> Add "evaluated_value" support to number types

- libcst/helpers/expression.py
- libcst/helpers/tests/test_expression.py
Similar to existing functionality for `Call` and `FunctionDef` nodes, it makes sense to be able to ask what the full name of a decorator is. Add that support.
existing tests, pyre.
> Add decorator support to get_full_name helper

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_qualified_name_provider.py
Example code:
```
obj = object()
obj.eval
```
The current QualifiedNameProvider provide the wrong qualified name `{QualifiedName("builtins.eval", QualifiedNameSource.BUILTIN)}` for `Name("eval")` in attribute `obj.eval`.
The names should be an empty set.
Unit test.
> [metadata][QualifiedNameProvider] don't provide qualified name for names in Attribute().attr

- CHANGELOG.md
- setup.py
As it says on the tin. There's nothing holding this release up so its time for a new one!
tox, pyre
> Bump LibCST to new release 0.3.1.

- libcst/__init__.py
- libcst/_version.py
- libcst/tool.py
- setup.py
Basically what it says on the tin. I moved the version to a constant that's accessible inside libcst namespace so I could use it in `libcst.tool`. However, it might be useful for consumers of libcst to know programmatically what version they're working with. There's some convoluted stuff in setup.py because I wanted to make sure this was loaded by file, not by module in order to remove any setup dependencies on existing libcst installations. However, this means there's a single source of truth for both deploying the package as well as getting the version from inside the package.
tox, pyre, ran `libcst --version` and saw it print the right thing, ran `python3 setup.py --help` and verified it parsed correctly with a version print inside it.
> Add a --version flag to `libcst.tool`, single-source version.

- libcst/codemod/_cli.py
- libcst/codemod/_context.py
- libcst/codemod/tests/test_cli.py
I want to add helpers to import nodes and in helper directory for getting the module/object/alias for an import in a way compatible with add/remove import transforms. Part of that includes support for relative imports. Until now, we had no way of figuring out the absolute package name from a relative one. So, add that support in preparation of closing that hole in LibCST.
Added some tests for the new helper method, also modified the noop codemod to print the package name of each file and looked it over for irregularities.
> Add support for current package to codemod context.

- libcst/_nodes/statement.py
- libcst/codemod/commands/ensure_import_present.py
- libcst/codemod/commands/tests/test_ensure_import_present.py
- libcst/codemod/visitors/_add_imports.py
- libcst/codemod/visitors/_gather_imports.py
- libcst/codemod/visitors/tests/test_add_imports.py
- libcst/codemod/visitors/tests/test_gather_imports.py
- libcst/helpers/__init__.py
- libcst/helpers/_statement.py
- libcst/helpers/tests/test_statement.py
This PR is split across three different commits. The end goal is to get easier insight into import statements with various helpers.
In the first commit, I add several helpers to LibCST in various places:
- `evaluated_name` and `evaluated_alias` on `ImportAlias`. I noticed a common pattern where we need to know the string name and alias for imports. This helps with that by taking lots of boilerplate away. It makes `ImportAlias` compatible with the existing import gathering and import adding visitors, as well as an upcoming import removal visitor.
- `get_absolute_module_for_import` (and a version that throws instead of returning `None`). It is actually quite tricky to resolve the absolute module of an import given the current module and an `ImportFrom` node. There are many edge cases. So, I …
> Add Various Import Helpers

- libcst/codemod/commands/convert_format_to_fstring.py
- libcst/codemod/commands/tests/test_convert_format_to_fstring.py
This closes a few holes in the format() to f-string codemod. Namely, it adds switches to some more dangerous behavior, and fixes the fact that we had a TODO for format specifications. This should be able to handle far more edge cases now.
Added several new tests.
> Augment format() -> f-string Codemod

- docs/source/codemods.rst
- libcst/codemod/_command.py
- libcst/codemod/visitors/__init__.py
- libcst/codemod/visitors/_add_imports.py
- libcst/codemod/visitors/_gather_exports.py
- libcst/codemod/visitors/_remove_imports.py
- libcst/codemod/visitors/tests/test_gather_exports.py
- libcst/codemod/visitors/tests/test_remove_imports.py
This was the last bit of codemod framework code that was incubated inside Instagram. This PR open-sources that code and improves it a bit by using the recently-added import helpers. This enables the existing code to handle relative imports successfully, and integrates removing imports into the codemod framework in the same manner as adding imports. With this PR in place, we have a consistent story around imports for everything except for references from type hints that are written as forward reference strings.
This PR copies the files to open-source, rewrites a few sections to use `libcst.helpers`, adds a ton of documentation and adds tests for relative imports since that is enabled by using `libcst.helpers`.
Existing and new tests, pyre, tox.
> Open-Source Import Removal Code

- docs/source/metadata.rst
- libcst/metadata/__init__.py
- libcst/metadata/span_provider.py
- libcst/metadata/tests/test_span_provider.py
This PR implements `ByteSpanPositionProvider` which tracks the positions of cst nodes using a pair of (offset, length) integers, representing
* the byte offset from the start of the file until the first non-whitespace character of the node
* the length of the node in bytes, not counting any trailing whitespace the node owns
Added unit tests.
> Add a provider for tracking node positions using byte offsets

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
In one of the use case, **the Scope Analysis consumed 6GB memory**.
The use case has lots of object creation (Call node) using keyword argument.
`Arg.keyword` is created as an `Assignment` and stored in the parent scope which doesn't make sense.
E.g. An "arg" `Assignment` was created and stored in `GlobalScope`.
```
call(arg=val)
```
Unless we create a `LocalScope` for `Call` node, no `Assignment` should be created in this case.
Adding a `LocalScope` for `Call` node probably won't be very useful since there won't be references.
For now, we just remove the `Assignment` creation.
This reduces memory usage from 6GB to 75MB and makes it **80X more memory** efficient for this specific benchmark.
Also include another small optimization which add slots to `Access`.
CC @zsol
Added test case and …
> Optimize Scope Analysis memory usage by removing unnecessary Assignment creation

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Calling `get_qualified_names_for` or `__contains__` for items not in the scope used to result in a `self._assignments[name]` call which inserted a new empty set into itself.
This was a problem because all iterators to assignments were invalidated. This PR prevents the above from happening.
> Make get_qualified_names_for and __contains__ not change the scope

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Aggregate access with the same name and batch add with set union as an optimization.
In worst case, all accesses (m) and assignments (n) refer to the same name,
the time complexity is O(m x n), this optimizes it as O(m + n).
This also changed the return of scope assignments from Tuple to Set to make it faster without creating Tuple.
Checked current use cases and all of them just iterate on the returned assignments which don't explicit use it as a Tuple. This change is safe.
@zsol 
Existing unit tests.
Test on a file with 70k lines with 50k access of the same name. Combine both the optimization of not visiting formatting info and this infer access optimization.
Before the optimization: `7min 49.90secs`
After both optimization: `2min 25.19secs` (3.2X faster)
> [ScopeProvider][optimization] use batch set union in infer_accesses

- libcst/metadata/scope_provider.py
Don't visit formatting information nodes.
Provide scope object for formatting information is not useful. In most cases, we just need scope for Name, Attribute, etc.
Remove those unnecessary visits makes the visitor run faster and keeps the code cleaner.
CC @zsol 
Existing unit tests.
> [ScopeProvider][optimization] don't visit formatting information nodes

- libcst/_nodes/expression.py
- libcst/_nodes/module.py
- libcst/_nodes/statement.py
- libcst/_nodes/tests/test_docstring.py
- libcst/helpers/tests/test_expression.py
Add `get_docstring()` to `Module`, `ClassDef` and `FunctionDef`.
Docstring is the first expression (ignoring comments and empty lines) of `Module`, `ClassDef` or `FunctionDef` and it needs to be a `SimpleString` or `ConcatenatedString`.
Note that `ConcatenatedString` can be a tree of nested `ConcatenatedString`. So we need to traverse the entire tree. It returns `None` if any part of the tree is a f-string.
The reason why docstring cannot be a f-string was discussed in https://bugs.python.org/issue28739.
References:
- `ast.get_docstring` https://docs.python.org/3/library/ast.html#ast.get_docstring
and https://github.com/python/cpython/blob/89aa4694fc8c6d190325ef8ed6ce6a6b8efb3e50/Lib/ast.py#L254
- PEP 257 https://www.python.org/dev/peps/pep-0257/
Unit tests.
> [helper] add get_docstring() to Module, ClassDef and FunctionDef

- docs/source/metadata_tutorial.ipynb
- libcst/_metadata_dependent.py
- libcst/metadata/tests/test_metadata_provider.py
Adds a more useful message to KeyError when a metadata provider is missing.  This is easy to trigger if you call `.resolve` and let it finish before accessing (because it clears) or if you forget to `.visit` on the MetadataWrapper instead of Module.
New test.
> Improve KeyError message for missing metadata

- libcst/_nodes/statement.py
- libcst/_nodes/tests/test_try.py
- libcst/_parser/conversions/params.py
Testing libcst against real-world code, this comes up a few times, probably from people used to C.  Instead of blanket requiring a space, only require the space if the type is a Name.
There are still many ways to make an invalid `except`, but this finds the most common.
Included tests fail before the fix, pass after.  There is a `test_invalid` that ensures the exception is still raised on the most obvious cases.
> Better validate `except` without a space after it.

- .circleci/config.yml
- setup.py
- stubs/hypothesmith.pyi
Previously, pyre only looks into stub/ and thus it doesn't understand setuptools.
By adding --preserve-pythonpath to pyre check, it understand setuptools. We no longer need hypothesmith empty stub file since the source code is typed.
Ci builds.
> [pyre] use --preserve-pythonpath to enable Pyre to read from site-packages

- libcst/codemod/visitors/_remove_imports.py
- libcst/codemod/visitors/tests/test_remove_imports.py
as title and was described in https://github.com/Instagram/LibCST/issues/258
New unit tests.
> RemovedNodeVisitor should not remove imports when references exist.

- libcst/_nodes/module.py
- libcst/_nodes/statement.py
- libcst/tests/test_tabs.py
- libcst/tests/test_type_enforce.py
- setup.py
- stubs/hypothesmith.pyi
- stubs/setuptools.pyi
> [typing] add missing type annotations

- libcst/codemod/commands/remove_unused_imports.py
- libcst/codemod/commands/tests/test_remove_unused_imports.py
Ran on an earlier version of this file:
```
❯ python -m libcst.tool codemod remove_unused_imports.RemoveUnusedImportsCommand libcst/codemod/commands/remove_unused_imports.py -u                                                                      normal
Calculating full-repo metadata...
Executing codemod...
0.01s 0% complete, [calculating] estimated for 1 files to go...--- /home/zsol/libcst/libcst/codemod/commands/remove_unused_imports.py
+++ /home/zsol/libcst/libcst/codemod/commands/remove_unused_imports.py
@@ -3,16 +3,14 @@
#
-from typing import Type, Generator
-from libcst.codemod import Codemod, VisitorBasedCodemodCommand
+from libcst.codemod import VisitorBasedCodemodCommand
from libcst.codemod.visitors import RemoveImportsVisitor
from libcst import Import, ImportFrom
-import asyncio …
```
> Add codemod command for removing unused imports

- README.rst
- libcst/__init__.py
- libcst/_nodes/tests/base.py
- libcst/_nodes/tests/test_atom.py
- libcst/_nodes/tests/test_dict.py
- libcst/_nodes/tests/test_funcdef.py
- libcst/_nodes/tests/test_list.py
- libcst/_nodes/tests/test_matrix_multiply.py
- libcst/_nodes/tests/test_set.py
- libcst/_nodes/tests/test_tuple.py
- libcst/_nodes/tests/test_with.py
- libcst/_nodes/tests/test_yield.py
- libcst/_parser/conversions/expression.py
- libcst/_parser/conversions/statement.py
- libcst/_parser/detect_config.py
- libcst/_parser/entrypoints.py
- libcst/_parser/grammar.py
- libcst/_parser/parso/python/tokenize.py
- libcst/_parser/production_decorator.py
- libcst/_parser/python_parser.py
- libcst/_parser/tests/test_detect_config.py
- libcst/_parser/types/config.py
- libcst/_parser/types/production.py
This adds support for machine-readable supported versions, and the minor changes necessary to support 3.0, 3.1, and 3.3.  This includes future detection for future Python 2 parsing, but isn't required here given the PEP 401 findings.
Machine-readable versions are at `libcst.KNOWN_PYTHON_VERSION_STRINGS`.
New included tests, and ran against my `python-grammar-changes` project.  Each entry should either have ".." or "oo" to say that the LibCST success matches that cpython version.
```
[tim@rygel python-grammar-changes]$ ../LibCST/.tox/py37/bin/python metarun.py
30 31 33 35 36 37 38
examples/py31-0002-with1.py                       oo oo oo oo oo oo oo 
examples/py31-0002-with2.py                       .. oo oo oo oo oo oo 
examples/py31-0002-with3.py                       .. oo oo oo oo oo …
```
> Support Python 3 syntax back to 3.0

- docs/source/codemods.rst
- libcst/codemod/visitors/__init__.py
- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
Basically move the [`apply_annotations`](https://github.com/facebook/pyre-check/blob/7ee7f4b15fc4666371e7538cc44931a298229a2d/client/apply_annotations.py) code from Pyre. I had discussed this with Jimmy Lai. The main motivation for moving it to libcst is that the code deals purely with libcst concepts like `CSTVisitor` and `CSTTransformer` and we want to use it in two separate projects: Pyre and MonkeyType.
This is not implemented as a normal Codemod because, instead of working on just one module, it works on two modules: the stub module from which to collect annotations and the source module to which to apply the annotations.
Added the tests as well.
> Apply type annotations from a stub.

- libcst/codemod/visitors/_add_imports.py
- libcst/codemod/visitors/tests/test_add_imports.py
@pradeep90 reported that `AddImportsVisitor` generates the added import alias in random order which make codemod unit test failed randomly.
In the example code like this, the order of `Any, Dict, List` is not deterministic.
```
"""
from typing import Any, Dict, List
from typing import Any, List
def foo() -> List[Any]: ...
def goo() -> Dict[Any, Any]: ...
""",
"""
from typing import Any
def foo():
return []
def goo():
return {}
""",
"""
from typing import Any, Dict, List
def foo() -> List[Any]:
return []
def goo() -> Dict[Any, Any]:
return {}
""",
```
Add new test case.
> [AddImportsVisitor] generate deterministic add import output by sorting the sets.

- libcst/codemod/_cli.py
It appears we're running out of file handles when running on large repo on OSX due to waiting until all files have been
processed to join/close the subprocesses.
This PR joins/closes them as they finish, resolving the issue.
```
$ python3 -m libcst.tool codemod {codemod_name} {direectory}
Calculating full-repo metadata...
Executing codemod...
Codemodding {file}
File "/Users/rwilliams/src/go/src/github.com/lyft/python-lyft-ingest/venv/lib/python3.6/site-packages/libcst/codemod/_cli.py", line 253, in _parallel_exec_process_stub
OSError: [Errno 24] Too many open files: '{file}'
Failed to codemod {file}
19.80s 24% complete, 01m 02s estimated for 741 files to go...Traceback (most recent call last):
File …
```
> Fix "Too many open files" errors when running on large repo on OSX

- libcst/codemod/_cli.py
When LibCST produces code with syntax error, the formatter raises exception but the error message was not useful. This surface the detailed error to make debug easier.
> [codemod] show errors from formatter subprocess call

- libcst/codemod/tests/codemod_formatter_error_input.py.txt
- libcst/codemod/tests/test_codemod_cli.py
Without the fix, it shows error like this and it's not useful to understand the cause.
```
File "/Users/jimmylai/github/LibCST/libcst/codemod/_cli.py", line 334, in _parallel_exec_process_stub
newcode = invoke_formatter(formatter_args, newcode)
File "/Users/jimmylai/github/LibCST/libcst/codemod/_cli.py", line 63, in invoke_formatter
encoding=None if work_with_bytes else "utf-8",
File "/Users/jimmylai/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
**kwargs).stdout
File "/Users/jimmylai/anaconda3/lib/python3.7/subprocess.py", line 487, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/jimmylai/github/libcst-env/bin/black', '-']' returned non-zero exit status 123.
Failed to codemod …
```
> [codemod] add integration test for show errors from formatter subprocess call

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
`get_qualified_names` now returns the most appropriate qualified name for both `import a.b.c` style imports as well as later references to them.
Added unit test.
> Add support for dotted imports in get_qualified_names

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Scope analysis encounters attribute accesses that don't refer to imports. These attribute accesses can have arbitrary expressions in the `Attribute` node, which the import access analysis is not prepared for. Instead of blowing up with an exception, just skip these accesses (which was the previous behavior).
Note that for a case like `foo().bar`, this change only skips access analysis for the outer `Attribute` node, `foo` will still be analysed.
Added two test cases.
Fixes #286
> Handle non-import attribute accesses gracefully

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
This will allow us to override existing types based on the stub.
Added test case.
> [apply-annotations] Add argument for ignoring existing annotations.

- libcst/codemod/commands/convert_namedtuple_to_dataclass.py
- libcst/codemod/commands/tests/test_convert_namedtuple_to_dataclass.py
Conversion of a NamedTuple class declaration to Python 3.7 `dataclasses.dataclass` type as an annotation. Perform removal of unused NamedTuple import and add the import of `dataclasses.dataclass` if not already imported. 
Updated test suite:
```
python -m unittest libcst.codemod.commands.tests.test_convert_namedtuple_to_dataclass
```
Run entire test suite:
```
tox test
```
> Add NamedTuple to dataclass conversion codemod

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
During scope analysis all attribute accesses are collected for matching on
import names. The matching code (specifically `_gen_dotted_names`) was not
prepared for all types of expressions. In particular, complex expressions like
`foo[0].bar.baz()` caused a `StopIteration` exception when `_gen_dotted_names`
calls itself recursively. The nested call doesn't yield any values, and so
calling `next()` on it raises.
This commit fixes these types of errors.
Added test case
> Fix StopIteration exception during scope analysis

- libcst/metadata/scope_provider.py
Follow up of https://github.com/Instagram/LibCST/pull/298
Make it more efficient and also fix the type annotation.
Existing tests.
> [scope] remove iter call to be more efficient

- CHANGELOG.md
- libcst/_version.py
Bump to new version for `ConvertNamedTupleToDataclassCommand` codemod command
> [release] Bump LibCST to new release 0.3.6

- README.rst
- docs/source/index.rst
FB Open Source links to Terms Of Use & Privacy Policy on homepage
see: https://7248-200896124-gh.circle-artifacts.com/0/doc/index.html
> Add fb open source required links

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_qualified_name_provider.py
When working on another branch, noticed:
```
import a
foo = a.bar
```
The qualified name of `a.bar` would get returned as `QualifiedName(name="a.b",...)`
- All tests still pass`tox`
- Check QualifiedName for `a.bar` is returned as "a.bar"
> Added maxsplit value in QualifiedName retrieval

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
ApplyTypeAnnotationsVisitor erases default values of positional-only and keyword-only args. See https://github.com/Instagram/MonkeyType/issues/198 for a repro
Added tests for the relevant issues in test_apply_type_annotations.py
> ApplyTypeAnnotationsVisitor: fix default value

- libcst/codemod/commands/tests/test_remove_unused_imports.py
- libcst/metadata/expression_context_provider.py
- libcst/metadata/tests/test_expression_context_provider.py
Fixes #318.
This brings LibCST in line with the built in ast module.
Changed/added tests + manually verified the following file is not touched by the remove unused imports codemod:
```
from a import b
b[0] = False
```
```
python -m libcst.tool codemod remove_unused_imports.RemoveUnusedImportsCommand test.py -u
```
> [ExpressionContextProvider] Make subscript values have a LOAD context

- libcst/metadata/scope_provider.py
Fixed minor typo ('as'  was repeated)
> Minor typo in scope_provider.py

- libcst/_nodes/op.py
- libcst/metadata/tests/test_position_provider.py
`PositionProvider` provides inconsistent `NotEqual` (whitespaces are included) compare to `Equal` (whitespace is not included). Issue was reported in #315.
Not sure why `NotEqual` was implemented differently.
Use `_BaseOneTokenOp` to keep the codegen consistent and add test cases.
Add new test cases.
> Fix NotEqual position issue

- tox.ini
To provide a developer with the ability to run `tox` commands on specific directories or files during local development. 
- run on a directory:
```
tox -e lint libcst/tests
```
- run on a file:
```
tox -e lint libcst/_typed_visitor_base.py
```
- run with no args:
(make sure all 246 files checked)
```
tox -e lint
```
- run on a directory:
```
tox -e autofix libcst/tests
```
- run on a file:
```
tox -e autofix libcst/_typed_visitor_base.py
```
- run with no args:
(make sure all 246 files checked)
```
tox -e autofix
```
- run specific test case:
```
tox -e py<version> libcst.tests.test_batched_visitor
```
- run with no args:
(make sure all 1727 tests run)
```
tox -e py<version>
```
> Optional args for tox commands

- libcst/metadata/full_repo_manager.py
- libcst/metadata/tests/test_full_repo_manager.py
A need for the ability to fetch cache for all paths at once became evident in a use case requiring some optimizations.
The ability to access the private `_cache` property of `FullRepoManager` would be useful in a case like this.
- Test case in `test_full_repo_manager`
- All tests pass
> FullRepoManager `cache` property

- libcst/codemod/commands/tests/test_remove_unused_imports.py
- libcst/codemod/visitors/_remove_imports.py
- libcst/codemod/visitors/tests/test_remove_imports.py
`RemoveUnusedImportsVisitor` always removed trailing commas from import statements, which caused the CST to always change. This is undesirable because it causes unnecessary post-processing (like formatting being applied) even if there were no "real" changes to the CST.
This PR changes visitor's behavior so that the trailing comma is only removed if the last alias is actually removed.
> Only remove trailing comma if the last alias is removed

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
Just as we special case "Type" when applying annotations here: https://github.com/Instagram/LibCST/blob/master/libcst/codemod/visitors/_apply_type_annotations.py#L166
We need to do the same in Subscripts
python -m unittest -v libcst.codemod.visitors.tests.test_apply_type_annotations
> [Pyre] Handle type subscripts when applying annotations.

- libcst/codemod/visitors/_add_imports.py
- libcst/codemod/visitors/tests/test_add_imports.py
Module docstring was reordered wrongly.
```
'''Docstring.'''
import typing
```
Became
```
from __future__ import annotations
'''Docstring.'''
import typing
```
Instead of
```
'''Docstring.'''
from __future__ import annotations
import typing
```
Added a test case.
> Insert imports after module docstring

- libcst/_nodes/statement.py
- libcst/_nodes/tests/test_import.py
- libcst/_nodes/tests/test_try.py
For `Try` statements we ensure that the bare except, if present, is at the last position.
For ImportAlias we ensure that the imported name is valid.
Fixes #287
Unit tests
> fix: improve validation for ImportAlias and Try statements

- libcst/_nodes/statement.py
- libcst/_nodes/tests/test_funcdef.py
- libcst/matchers/__init__.py
> fix: allow ParenthesizedWhitespace before params in FuncDef

- CHANGELOG.md
- libcst/_version.py
Bump LibCST to new release 0.3.8
tox -e py37
> [release] Bump LibCST to new release 0.3.8

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Issue was reported in https://github.com/Instagram/LibCST/issues/329, `FunctionDef.name` has scope object associated but `ClassDef.name` doesn't.
This PR fixes the inconsistency.
Updated unit tests.
> [scope] add scope for ClassDef.name node

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Add scope for ImportAlias.
Import node and ImportFrom node already have scope object associated. Also add test cases for them.
Updated unit test.
> [scope] add scope for ImportAlias

- docs/source/codemods.rst
- libcst/codemod/commands/remove_unused_imports.py
- libcst/codemod/commands/tests/test_remove_unused_imports.py
- libcst/codemod/tests/codemod_formatter_error_input.py.txt
- libcst/codemod/visitors/__init__.py
- libcst/codemod/visitors/_gather_comments.py
- libcst/codemod/visitors/_gather_string_annotation_names.py
- libcst/codemod/visitors/_gather_unused_imports.py
- libcst/codemod/visitors/_remove_imports.py
- libcst/codemod/visitors/tests/test_gather_comments.py
- libcst/codemod/visitors/tests/test_gather_string_annotation_names.py
- libcst/codemod/visitors/tests/test_gather_unused_imports.py
This PR adds support for detecting imports being used by string type
annotations, as well as imports suppressed by comments.
It breaks up the existing visitor into multiple smaller, single-purpose
visitors, and composes them together.
TODO:
existing and new tests
> [RemoveUnusedImports] Support string type annotations

- .pyre_configuration.example
Missing a comma
Try pyre with the example configuration
> Fix syntax error in .pyre_configuration.example

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
When importing things like `import os.path` and using it as `os.path.join("a", "b").lower()`,
references ended up being in the `["os"]` assignment instead of `["os.path"]`.
This fixes the problem by updating the dotted names generator in the scope provider·
```
tox -e py37
```
> Fix dotted names

- libcst/codemod/commands/tests/test_remove_unused_imports.py
- libcst/metadata/scope_provider.py
Fixes enclosed arguments like `c.d` in `x.y(c.d()).z()` were badly being resolved as `x.y` instead.
This also clarifies the intent in `infer_accesses()` so it no longer shadows variable `name` and also fixes the case where no node is actually found in the scope.
Run tests
> Fix enclosing attribute for attributes in call arguments

- libcst/codemod/_command.py
kwonlydefaults is Optional, fix pyre error about it
Run existing tests + pyre
> Fix pyre error: kwonlydefaults is Optional

- setup.py
#331 reports that tests fail in a certain environment; these messages could be more obvious but are because of missing files.
The relevant files were not included in the manifest generated by `setup.py egg_info` before, and now are.
> Include missing test data in install

- libcst/_nodes/expression.py
- libcst/_nodes/tests/test_namedexpr.py
Spaces around walrus operator are not required. Fixes #367
Unit test
> fix: spaces around walrus operator

- libcst/metadata/type_inference_provider.py
Since the stdout/err is being captured from this invocation, using the noninteractive flag will make the output much more readable and avoid special characters for terminal pretty-printing.
> Call pyre query with noninteractive logging

- libcst/matchers/_matcher_base.py
- libcst/matchers/tests/test_extract.py
`SaveMatchedNodes` within sequences was not working as expected, the fixes in this PR are:
- Fixes #337 the returned matched sequence now reflect the original match and it's not extended until the end of the original sequence
- Fixes #338 a node matched without a wildcard is now returned as a node and not a sequence 
Unit tests
> fix: correctly extract wildcard matchers

- libcst/codemod/visitors/_gather_comments.py
- libcst/codemod/visitors/_gather_string_annotation_names.py
- libcst/codemod/visitors/_gather_unused_imports.py
These gatherer visitors are supposed to be reusable, but the matchers make them
* unnecessarily slow
* hard to configure
So this PR eliminates the matchers and uses a more standard visitor API.
Existing tests
> replace matchers with explicit visitation in gatherers

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Access references with this type come from an annotation.
Run tests.
> Annotation access

- libcst/codemod/visitors/_gather_exports.py
- libcst/codemod/visitors/tests/test_gather_exports.py
This flags exports of undefined names and safely handles more cases for `__all__`.
It should now handle:
```py
import os
__all__, _ = ["os"], []
```
> Handle more cases for __all__

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
This adds support for string annotations to ScopeProvider
Run tests
> Handle string annotations in ScopeProvider

- libcst/metadata/scope_provider.py
`Literal` is some times imported from `typing_extensions`
Run tests
> Literal could be imported from typing_extensions too

- CHANGELOG.md
- libcst/_version.py
Bump to version 0.3.10. Changes detailed in CHANGELOG.md
```sh
tox -e py37
```
> Bump to version 0.3.10

- libcst/metadata/parent_node_provider.py
@Kronuz called out that the return type of `ParentNodeProvider` should NOT be an `Optional`.
That's true because the `original_node` set as metadata is always a `CSTNode`.
https://github.com/Instagram/LibCST/blob/c023fa7c4caff3fd2b3946080f9a58b539b10363/libcst/metadata/parent_node_provider.py#L18-L21
Existing tests.
> [metadata] update return type of ParentNodeProvider to be CSTNode

- .fixit.config.yaml
- libcst/_parser/parso/pgen2/generator.py
- libcst/_parser/parso/python/tokenize.py
- libcst/_parser/parso/tests/test_utils.py
- libcst/_parser/parso/utils.py
- libcst/_parser/tests/test_detect_config.py
- libcst/codemod/_cli.py
- libcst/codemod/commands/ensure_import_present.py
- libcst/codemod/commands/remove_unused_imports.py
- libcst/codemod/visitors/tests/test_gather_unused_imports.py
- libcst/matchers/_matcher_base.py
- requirements-dev.txt
- tox.ini
- add Fixit to tox -e lint
- run apply_fix except for UseFstringRule and CompareSingletonPrimitivesByIsRule.
- UseFstringRule: f-string is only supported in Python 3.6. Use f-string requires drop the support of Python 3.5 which is probably ok. Leave as future work.
- CompareSingletonPrimitivesByIsRule has an issue and the autofix was wrong. Will follow up in Fixit.
CI builds
> [CI] add Fixit to tox -e lint

- libcst/codemod/visitors/_remove_imports.py
- libcst/codemod/visitors/tests/test_remove_imports.py
When removing import aliases, comments often get mangled (see test cases for details). This PR fixes comment handling.
Added test case
> Removing an import alias with a trailing standalone comment should preserve the comment

- libcst/matchers/tests/test_findall.py
- libcst/matchers/tests/test_matchers_with_metadata.py
- libcst/metadata/expression_context_provider.py
- libcst/metadata/tests/test_expression_context_provider.py
closes #393  by extending ExpressionContextVisitor
Adds basic tests for the extension
> Use STORE for {Class,Function}Def.name in ExpressionContextProvider

- libcst/codemod/visitors/_remove_imports.py
- libcst/codemod/visitors/tests/test_remove_imports.py
The comment preserving logic introduced in #392 assumed that in an `ImportFrom` node, `ImportAlias`es have a `comma` property (except for the last one). That's only true if the `ImportFrom` node is parsed from actual source, but isn't necessarily true if it's constructed manually.
This PR adds a defensive check for the existence of a proper `Comma` node, and in case it doesn't exist (because it's a `MaybeSentinel`), the logic now just moves over the `Comma` node from the alias that's about to be removed.
Added a test case that adds a new `ImportAlias` node manually (with `comma=MaybeSentinel.DEFAULT`), then removes the next alias.
> fix RemoveImportsVisitor crash when ImportAlias is inserted without comma

- libcst/_nodes/statement.py
- libcst/_nodes/tests/base.py
- libcst/_nodes/tests/test_assign.py
- libcst/matchers/__init__.py
Closes #391 
Changes to `libcst/matchers/__init__.py` performed by `tox -e codegen`
I couldn't find any relevant tests to extend but would be happy to write one.
> Use correct type for AugAssign and AnnAssign target

- libcst/_parser/types/tests/test_config.py
- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
- libcst/tests/test_type_enforce.py
Add support for string annotations in type aliases.
Run tests.
This will support things like:
```py
from typing import Dict, Union
from video import VideoType
VideoDict = Dict[str, Union[str, int, "VideoType"]]
```
And get a properly referenced `VideoType`.
> Support string annotations for type aliases

- CHANGELOG.md
- libcst/_version.py
Bump to version 0.3.13
- Use correct type for AugAssign and AnnAssign target [#396](https://github.com/Instagram/LibCST/pull/396)
- Support string annotations for type aliases [#401](https://github.com/Instagram/LibCST/pull/401)
> Bump to version 0.3.13

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
fix is_annotation for types used in classdef base and assign value
discussion
tox -e py37
tox -e autofix
> fix is_annotation for types used in classdef base and assign value

- libcst/codemod/_cli.py
- libcst/codemod/commands/convert_format_to_fstring.py
- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/helpers/_statement.py
- requirements-dev.txt
The recent Fixit releases contained new linters and behavior which caused master to be broken, causing all pull requests to be red. This PR pins `black`, `fixit`, and `isort` to a specific revision to make sure this doesn't happen again, and fixes lint violations so master can be green again
`tox -e lint -r`
> Pin linters

- libcst/codemod/_cli.py
- libcst/codemod/commands/convert_format_to_fstring.py
- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/helpers/_statement.py
- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
- requirements-dev.txt
This PR makes sure scope analysis visits nodes under a `ConcatenatedString`. This is important because `ConcatenatedString`s may contain `FormattedString`s which can contain further expressions. We only need to go deeper if the concatenated string is not part of a type annotation though (those can't contain f-strings).
Fixes #410.
Added unit test.
> [scope] Visit concatenated f-strings

- libcst/codemod/_cli.py
- libcst/codemod/_dummy_pool.py
This PR refactors some of the codemod CLI internals to:
* use a simple "execution configuration" dataclass instead of passing a number of kwargs around
* use the default `multiprocessing.Pool()` instead of managing processes and queues by hand
* simplify the special-casing of a single file being processed by `parallel_exec_transform_with_prettyprint` to use a synchronous stub "multiprocessing" Pool instead
These changes pave the way to surfacing `_execute_transform()` (née `_parallel_exec_process_stub()`) as a public API, which would be useful for writing wrapper tools (like `django-codemod`, via which I came across LibCST in https://github.com/browniebroke/django-codemod/pull/233) that could opt-in to doing either parallel or serial codemod processing as they like.
This is an internal …
> Codemod CLI multiprocessing simplification

- libcst/_nodes/tests/test_namedexpr.py
- libcst/_parser/conversions/expression.py
Previous behavior treated it as identical to equal, making a kwarg; it should
instead be a positional arg.  Includes several tests to make sure that
whitespace handling is correct.
Fixes #416
Includes new tests that were failing before.  I had some trouble ensuring the whitespace ended up in the right spot during development, so this includes a few probably unnecessary tests out of a general distrust that I did it right.
> Correct handling of walrus operator in function args

- libcst/_nodes/tests/test_atom.py
- libcst/_parser/conversions/expression.py
Fixes #388
I'm kind of dogsciencing this, since there doesn't appear to be a formal grammar for f-strings. I tested a few other languages features and am pretty confident the only major feature that works in 3.8 that we didn't have was bare generator expressions.
Includes new test, also tested on John's longer example.
> Allow generator expressions in f-strings

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
This PR makes sure references are never attached to assignments that are declared later than the access (but still in the same scope). It does so by keeping track of the relative ordering of accesses to assignments, through the inclusion of an `__index` member in both. The idea is to increment the index every time an assignment "happens" in a scope. This is a bit tricky because for `a = b`, the right hand side cannot refer to variables on the left side even if the left side is visited first.
Fixes #326 
Added extensive test case for a variable shadowing in a class/global scope scenario.
> [scope] keep track of assignment/access ordering

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Handle `cast("Type", object)` so `Type` is properly referenced in the scope.
Run tests
> Handle string type references in cast()

- CHANGELOG.md
- libcst/_version.py
> bump version to 0.3.14

- libcst/_nodes/tests/test_atom.py
- libcst/_parser/conversions/expression.py
- libcst/_parser/parso/python/tokenize.py
This is a port of https://github.com/davidhalter/parso/pull/160 plus a fix to yield expressions
A couple of new tests, but primarily tested in https://github.com/davidhalter/parso/pull/160
> Support Named Unicode Characters in f-strings

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Casted objects weren't being referenced. i.e., in:
```
from typing import cast
from module import SomeType, SomeObject
casted = cast("SomeType", SomeObject)
```
`SomeObject` ended up not being referenced.
Run tests
> Fix referencing of remaining objects in cast()

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
This change fixes attaching accesses to the right assignment in list comprehensions, so in
```
a = 1
[a for a in [1,2,3]]
```
The `a` at the beginning of the list comprehension is now attached to the `a` declared after `for` instead of the declaration on the first line.
> fix assignment/access ordering in comprehensions

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
When handling subscripts, `cast()`, and potentially others such as `TypeVar()` and `NewType()`, were being treated as potential string type hints, resulting in snippets like the following failing with a `ParserSyntaxError`:
```py
cast(Dict[str, str], {})["from"]
```
Run tests
> Fix for not parsing subscripts such as cast()["from"]

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
When visiting `for ... in ... :` statements, the scope provider was incrementing the assignment counter _after_ the entire `For` statement was visited. This meant that all accesses to `For.target` in `For.body` were potentially attached to the wrong scope. The only exception to this was when the scope of the `For` statement was in the global scope, in which case the fallback logic accidentally saved us (because for the global scope, `scope.parent == scope`).
This PR fixes the bug by customizing the way `ScopeProvider` visits `For` statements, and increments the assignment counter directly after visiting `For.target`.
Added a test case.
> Handle scope ordering in For statements

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
While investigating #430 I realized that scope provider might attach accesses to assignments AFTER the access in the global scope. This PR fixes that bug.
Added test case and verified it fails before this PR.
> Don't allow out of order accesses in the global scope

- libcst/matchers/_visitors.py
- libcst/matchers/tests/test_decorators.py
These unions were introduced in Python 3.10 and do not define `__origin__`,
so some extra checks are necessary to identify then. Since there is not
yet a 3.10 build, a somewhat hacky test was added to simulate one of
these new Unions.
Resolves #414.
Existing + new unittests. Also tested locally in an environment supporting new Unions.
> Support PEP-604 style unions in decorator annotations

- libcst/codemod/visitors/_gather_exports.py
- libcst/codemod/visitors/tests/test_gather_exports.py
Add support for gathering exports in `__all__` augmented assignments, such as:
```
import os
__all__ = []
__all__ += ["os"]
```
Run existing tests
> Gathering exports in augmented assignment statements

- libcst/metadata/expression_context_provider.py
- libcst/metadata/tests/test_expression_context_provider.py
- libcst/metadata/tests/test_scope_provider.py
This PR makes scope provider assign a `STORE` expression context to the left hand side of a walrus operator. So, in an `x := y` expression, `x` should have `ExpressionContext.STORE` as its expression context metadata.
Added unit tests.
> Walrus operator's left hand side now has STORE expression context

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
Caught this bug while running codemods, the result was that stubs for functions with parameter annotations, but without return annotations would not be annotated.
`python -m unittest -v libcst.codemod.visitors.tests.test_apply_type_annotations`
> ApplyTypeAnnotations: apply parameter annotations even if no return type is declared

- libcst/codemod/_cli.py
Per #435, any codemod which is implemented with a `lambda` cannot be run on more than one file at time.  That's because `pickle` limitations mean we can't use a process pool, and so this patch ensures that we *don't* use a process pool for `jobs=1` and thus enables a "just run serially" workaround.
This is also something of a performance optimisation, since starting a single process to do all the work is likely to take longer than just doing it in the current process.
> Work around Windows problem by using dummy pool for `jobs=1`

- docs/source/metadata.rst
- libcst/codemod/_codemod.py
- libcst/metadata/__init__.py
- libcst/metadata/full_repo_manager.py
- libcst/metadata/name_provider.py
- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_name_provider.py
This new provider resolves names to their fully qualified versions, and is capable of dealing with relative imports, addressing the same issue as #461.
Closes #460, closes #282.
This PR depends on #464 
Added unit tests.
> Add FullyQualifiedNameProvider

- libcst/_nodes/tests/test_atom.py
- libcst/_parser/parso/python/tokenize.py
Fixes the reported issue by reverting to the regex used before 02fc4401bc3313f0db109d86d1b84c6b35abba5a when raw.
I am not 100% sure checking just top of stack is enough, however.  I wish there was a conformance suite for f-strings.
Includes new test case
> Improve handling of raw fstrings (#462)

- CHANGELOG.md
- libcst/_version.py
- Add FlattenSentinel to support replacing a statement with multiple statements [#455](https://github.com/Instagram/LibCST/pull/455)
- Add BuiltinScope [#469](https://github.com/Instagram/LibCST/pull/469)
- Add FullyQualifiedNameProvider [#465](https://github.com/Instagram/LibCST/pull/465)
- Split QualifiedNameProvider out from libcst.metadata.scope_provider [#464](https://github.com/Instagram/LibCST/pull/464)
- Exception while parsing escape character in raw f-strings [#462](https://github.com/Instagram/LibCST/issues/462)
> Bump version to 0.3.18

- libcst/metadata/type_inference_provider.py
- libcst/tests/test_pyre_integration.py
https://github.com/Instagram/LibCST/issues/472
Switches to use `subprocess.run` instead of `Popen.communicate` which will automatically kill child process for us. Also removed the usage of `shell=True` because it is unnecessary and can be a [security concern](https://docs.python.org/3/library/subprocess.html#security-considerations). 
Updated existing unit tests. 
Tested manually (with `python3 -Wdefault test_libcst.py` as referenced in https://github.com/Instagram/LibCST/issues/472) to ensure the ResourceWarning went away and Zombie processes are not spawned.
`tox -e py37`
> Fix leaking processes from TypeInferenceProvider

- libcst/metadata/tests/test_type_inference_provider.py
- libcst/metadata/type_inference_provider.py
https://github.com/Instagram/LibCST/issues/475
`TypeInferenceProvider` crashes if an empty `cache` is passed to it, which resulted in the creation of [PLACEHOLDER_CACHES](https://github.com/Instagram/Fixit/blob/1f11c185c0541d419ada74fb938f4ac78f122971/fixit/common/full_repo_metadata.py#L23) in Fixit. I'm working on a [PR](https://github.com/Instagram/Fixit/pull/182) to allow a user to pass into Fixit no providers, and found this bug via this [conversation](https://github.com/Instagram/Fixit/pull/31#discussion_r452945560).
The fix itself is very simple. 
Added a unit test.
> Fixes TypeInferenceProvider breakage with empty cache.

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_name_provider.py
When `scope.get_qualified_names_for()` is called with a node that's an `Assignment`, return the qualified name for that node instead of all the assignments for the same name.
For example:
```
if False:
def f(): pass  # {"f"}
else:
from a import f  # {"a.f"}
f()  # {"f", "a.f"}
```
Before this PR, all three nodes had the same set of qnames returned (`{"f", "a.f"}`).
Will add tests before merging.
> Return more specific QNames for assignments

- libcst/metadata/name_provider.py
While checking out the cods for the recently added `FullyQualifiedNameProvider`, I noticed that one link to a class wasn't properly handled by Sphinx:
I think the idea was to add an `s` at the end of the class name since we're talking about multiple of them, but I couldn't find how to make the `s` stick, so I've reworded a bit.
Alternative solutions I considered, with the reason why I didn't go for them:
- Specify a title with the "s" (`` :class:`QualifiedNames <QualifiedName>` ``): altering the class name might confuse people
- Add a space between the class name and the "s": formatting looks off
- Remove extra markup/formatting: seems like a step back vs having links to the class docs.
Check the docs output
> Fix formatting for link to QualifiedName class in docs

- libcst/codemod/_cli.py
running codemodding fails due to passing an empty environment `env={}` rather than `env=None` according to the Python spec.
`Note If specified, env must provide any variables required for the program to execute. On Windows, in order to run a side-by-side assembly the specified env must include a valid SystemRoot.
`
by specifying env=None things work smoothly on Windows 10
fixes: #494 
I have only performed limited testing on Windows, but this should be validated across all supported platforms.
My assumption that this is already part of the CI/CD tests
> fix codemodding on windows 

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
**What?**
I added tests of how TypeAnnotationsVisitor reacts to
- stubs that ignore decorators and the async keyword
- stubs that lack parameter and/or return annotations where
a callable has them.
I discovered one case where TypeAnnotationsVisitor didn't do what
I want it to do: if we're missing a return annotation in the stubs
but have one in our function and `overwrite_existing_annotations` is
set, we'll actually strip out the existing annotation. So I tweaked
the logic to only use the annotation from the stub if it is nonmissing.
**Why?**
I'm working on a project (pyre infer) that depends on
TypeAnnotationsVisitor, and a problem we've run into is that we don't
yet have perfect logic for resolving imports in a way that's
sufficiently sensitive to local context to be good for codemods - …
> TypeAnnotationsVisitor: don't truncate function return type

- .gitignore
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
No changes to production code, just adding tests to make the existing
logic self-documented and regression-proof.
This is an important property for certain use cases, so it
makes sense to verify it in tests so that we can safely
depend on it.
At present, the reason we want to be able to rely on this is:
- at the moment, imports added by infer can make pysa traces
hard to understand, because the line numbers are off
- if we add the ability to use fully-qualified string annotations
for the stubs from infer, then we can do so without adding
any import lines and pyre will understand the types.
The goal here is to have LibCST's current TypeAnnotationsVisitor
behavior - which handles some types of imports and not others -
be well-documented in a test.
The reason is that import handling bugs are …
> Add tests verifying TypeAnnotationsVisitor current behaviors

- CHANGELOG.md
- libcst/_version.py
- Don't reset subprocess environment to fix codemodding on windows [#495](https://github.com/Instagram/LibCST/pull/495)
- TypeAnnotationsVisitor: don't truncate function return type [#499](https://github.com/Instagram/LibCST/pull/499)
- Docs: Fix typo [#492](https://github.com/Instagram/LibCST/pull/492)
> bump version to 0.3.20

- .github/workflows/build.yml
- requirements-dev.txt
- tox.ini
The previous codecov upload had a few shortcomings.
- it ran within tox
- it re-ran tests unnecessarily
I've moved this to run w/ gh actions
See https://github.com/lpetre/LibCST/runs/3302352659
and https://codecov.io/github/lpetre/LibCST/commit/8311866beeec0f1571f89fcc4c6a357c453de273
> Switch code coverage from tox => gh actions

- .github/workflows/.pyre_configuration.template
- .github/workflows/build.yml
This takes the runtime of the CI from ~8 minutes to <5 mins.
There is some unfortunate duplication, and I wish `needs` could depend on one matrix configuration.
Otherwise I'm very happy with this change.
This also enables me to ship windows testing, as I don't rely on tox anymore.
See https://github.com/lpetre/LibCST/actions/runs/1121624876
> Split up some larger CI/tox steps into separate jobs

- .github/workflows/build.yml
- libcst/codemod/_cli.py
- libcst/codemod/tests/test_cli.py
I've added windows testing to the github action CI.  Some tests fail, so I've updated the _calculate_module method to use PurePath better than before.
See CI run
> Windows CI support

- libcst/tests/pyre/simple_class.json
- libcst/tests/test_pyre_integration.py
- requirements-dev.txt
- setup.py
Bump the version of pyre to the latest, 0.0.41 is ancient.
```
pip install -r requirements-dev.txt
```
and the install went okay.
I'm pretty sure this is going to lead to a huge number of errors (I get pages of them on my computer), putting the PR up partly to see what the CI results look like and partly to get feedback about how to handle it.
> Bump pyre-check to latest version

- libcst/codemod/visitors/tests/test_apply_type_annotations.py
The existing two tests didn't make it clear what exactly we wanted
to verify, which is two things:
- that we can successfully annotate async functions with decorators
- that it doesn't matter whether or not the async and decorator
information is part of the stubs - we need it to be permissible
because a "real" stubs file would have this, but stubs generated
by tools like pyre infer shouldn't need to care, they only
really need to care about types
```
> python -m unittest libcst.codemod.visitors.tests.test_apply_type_annotations
..............................................
Ran 46 tests in 1.665s
OK
```
> Improve the tests of annotating async / decorator functions

- libcst/metadata/tests/test_type_inference_provider.py
- libcst/metadata/type_inference_provider.py
- libcst/tests/pyre/.pyre_configuration
- libcst/tests/pyre/simple_class.json
- libcst/tests/test_pyre_integration.py
Pyre command for type inference provider has one of its params quoted and causing the Pyre to fail to parse the command line.
Added unit test to generate the cache and compare with the expected result.
> Fix pyre command for type inference provider

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
Add a new argument to `ApplyTypeAnnotationsVisitor` that will trigger it
to add a `from __future__ import annotations` import to the top of a module.
This is a flag because it won't work on python 3.6 (in that case, users should
go in and manually quote types as needed or use quoted type names in the
stub file to begin with).
But for python 3.7+ it is a powerful tool to make adding
type annotations safer - malformed types (including types that are actually
valid for typecheckers like `os.PathLike[str]`) won't lead to runtime errors
and it's safe to use types from the current module anywhere without quoting them.
NOTE: This change should be merged only after we've merged
https://github.com/Instagram/LibCST/pull/539
to keep a clean history.
```
> python -m unittest …
```
> Use `from __future__ import annotations` in ATAV

- libcst/codemod/visitors/_apply_type_annotations.py
We have type hints on LibCST but pyre doesn't seem to be fully hooked up.
As a result, the code was fully annotated, and was type-error-free at
runtime, but had multiple places where pyre complained either due to
type refinement not working or type errors coming from branches of
the code that weren't reachable but couldn't be statically ruled out.
I ran unit tests, and vendored the changes into the pyre project to see that they
typecheck.
> Fix typing errors on ATAV

- requirements-dev.txt
The pinned version of black is failing in 3.9.8 during one of the codemod tests.
Upgrade black
python -m unittest libcst.codemod.tests.test_codemod_cli.TestCodemodCLI
> Upgrade black to fix errors in 3.9.8

- libcst/codemod/tests/test_codemod_cli.py
This test is breaking in #548 
python -m unittest libcst.codemod.tests.test_codemod_cli
> Pass absolute path to codemod test

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
This is the same behavior as cPython.
I've also rewritten the test that was relying on this exception to check where type parsing was happening
```
(libcstvenv) lpetre@lpetre-mbp LibCST % python -m unittest libcst.metadata.tests.test_scope_provider.ScopeProviderTest          
................................................s..
Ran 51 tests in 2.834s
OK (skipped=1)
(libcstvenv) lpetre@lpetre-mbp LibCST % 
```
> Swallow parsing errors in string annotations.

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
```
TypeVar("T", "int")
TypeVar("T", func("int"))
```
To correct handle these nested function calls I've turned the type hint tracking in the ScopeVisitor into a stack rather than a set.
python -m unittest libcst.metadata.tests.test_scope_provider
> Stop parsing string annotations when no longer in a typing call

- .github/workflows/build.yml
- setup.py
When `LIBCST_NO_LOCAL_SCHEME` is set while packaging, the local scheme will be removed from the version number (i.e. `0.3.22.dev16` instead of `0.3.22.dev16+g5c05001.d20211118`).
```
env LIBCST_NO_LOCAL_SCHEME=1 python setup.py sdist
ls dist/libcst-0.3.22.dev16.tar.gz
```
> disable setuptools local scheme when env var is set

- libcst/metadata/tests/test_scope_provider.py
I want to improve the coverage of the scope provider when imports interact with overwrite statements
```
(libcstvenv398) lpetre@lpetre-mbp LibCST % python -m unittest libcst.metadata.tests.test_scope_provider.ScopeProviderTest
...................................................
Ran 51 tests in 2.306s
OK
```
> Test overwriting imports w/ global and nonlocal stmts

- libcst/metadata/scope_provider.py
Correctly records scope assignments and simplifies some logic of resolving target scope.
python -m unittest libcst.metadata.tests.test_scope_provider
> Correct and simplify logic of recording assignments

- libcst/metadata/scope_provider.py
Move _NameUtil.find_qualified_name_for ... method inside Assignment classes.
For non imports we move this implementation inside Assignment.
For Imports we move this implementation inside ImportAssignment. 
python -m unittest libcst.metadata.tests.test_scope_provider
> Move find_qualified_names_for in the Assignment class.

- .gitignore
I noticed git complaining after I built the native parser.
> .gitignore shared-object built artifacts

- .github/workflows/build.yml
This should fix the failing pypi publish steps. TLDR there's a misfeature in `actions/checkout@v2` that fails to pull down tags. See https://github.com/actions/checkout/issues/290
> Fix CI publish to test.pypi.org

- .github/workflows/build.yml
This will get the built wheel to not have a local scheme, so they can be uploaded to test.pypi.org, then the upload will happen in a separate job, once all the binary wheels are built. Source dist is also built in this job.
> Fix pypi upload CI step

- .github/workflows/build.yml
Don't waste capacity by running checks twice on pull requests originating from a branch on the same repo.
> only run CI on pushes to main and pull requests

- libcst/codegen/tests/test_codegen_clean.py
It's nice that the tests warn us if you need to rerun code generation, but we don't actually document how to run code generation anywhere so every time I hit the failures I get frustrated trying to remember!
I thought about adding it to the README but I'm not actually sure it adds any value - instead, why not add it to the relevant failures. That way the codegen instructions aren't adding noise to the general getting-started docs, but they are right there whenever we need them.
In a branch where I added lpar and rpar to `With` statements, I ran
```
> python -m unittest libcst.codegen.tests.test_codegen_clean
FFF
======================================================================
FAIL: test_codegen_clean_matcher_classes (libcst.codegen.tests.test_codegen_clean.TestCodegenClean)
Verifies …
```
> Add instructions to codegen test failures

- native/Cargo.lock
- native/libcst/Cargo.toml
The native bindings need some unreleased features since rust-peg 0.7.0, but don't yet compile with 0.8.0, so we pin that dependency on an unreleased version.
I'll work on a PR to update the parser for peg 0.8.0, but until then this should help people build it.
it compiles :)
> Pin rust-peg dependency

- README.rst
Our README said to `pip install -e .` for type checking, but at this point that won't work
unless `cargo` is on the `PATH`, so I thought we should add some instructions.
I verified that having cargo and python should be enough by building LibCST in a
docker container, see https://github.com/stroxler/dockerfiles/tree/main/LibCST-minimal
> Add a `Building` subsection to the `Developing` docs

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
Matches signatures on shape, and on compatibility of existing annotations if `overwrite_existing_annotations` is False.
Matches posargs with different names if `strict_posargs_matching` is set to False
> Use precise signature matching when inserting function type annotations

- libcst/codemod/visitors/_apply_type_annotations.py
the method is already being called without the `node` argument here: https://github.com/Instagram/LibCST/blob/main/libcst/codemod/visitors/_apply_type_annotations.py#L274
> Remove unused argument to handle_Index

- libcst/codemod/commands/convert_type_comments.py
- libcst/codemod/commands/tests/test_convert_type_comments.py
Summary:
This codemod is intended to eventually handle all type comments from
PEP 484. This is a partial implementation specifically handling
assignment type comments, which as of PEP 526 are better dealt
with using AnnAssign nodes.
There is more work to do because there are two other kinds of
comments to support: function heading comments and function parameter
inline comments. But the PEP 526 functionality is complete so I feel
like it's worth having a PR / CI signals / code review at this stage.
Implementation Note:
It's a little weird that inside the transform we serialize small bits of the CST back
to code in order to use the `ast` module, but that's the most robust way to get
type comments and guaranteed to be PEP 484 compliant. Perf isn't an issue here
and I discussed with @zsol, …
> Codemod for PEP 484 Assign w / type comments -> PEP 526 AnnAssign

- libcst/codemod/commands/convert_type_comments.py
- libcst/codemod/commands/tests/test_convert_type_comments.py
In the previous PR, I added basic support for converting an
Assign with a type comment to an AnnAssign, as long as there was
only one target.
This PR handles all fully PEP 484 compliant cases:
- multiple assignments
- multiple elements in the LHS l-value
We cannot handle arity errors because there's no way to do it. And
we don't try to handle the ambiguous case of multiple assignments with
mismatched arities (PEP 484 isn't super clear on which LHS is supposed
to pick up the type, we are conservative here). The ambiguous case is
probably very uncommon in real code anyway, multiple assignment is not
a widely used feature.
NOTE: my local pyre is complaining and I don't understand it, putting
a PR up anyway to see what CI does.
There are new test cases covering:
- multiple elements in the LHS …
> Full handling for applying type comments to Assign

- libcst/codemod/commands/convert_type_comments.py
- libcst/codemod/commands/tests/test_convert_type_comments.py
For both `For` and `With`, we convert a statement with a type comment into multiple
statements, with SimpleStatementLines containing type declarations (i.e. AnnAssign statements)
preceding the original For / With.
Unit tests - added tests of both transforms and cases (e.g. arity errors, multiple with bindings)
that we don't support because the PEP 484 spec doesn't.
> Add support for For and With

- libcst/codemod/commands/convert_type_comments.py
- libcst/codemod/commands/tests/test_convert_type_comments.py
I've tested all of the edge cases I know of: type comments in various
locations, non-type-comments, arity mismatches where we should skip,
etc.
Assuming that all type comments parse, all the cases I know of are
now handled correctly.
I'll make a separate PR later this week to deal with SyntaxErrors
when parsing types, because that is cross-cutting and not specific to
FunctionDef; it's probably going to be most easily solved with
some kind of decorator.
> Support FunctionDef transformations

- native/libcst/Cargo.toml
In #613 people reported being unable to compile LibCST on rustc `1.52.1`. This PR specifices [the minimum version required](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) to compile LibCST.
> Specify minimum rust toolchain version

- .github/workflows/build.yml
- README.rst
- pyproject.toml
- requirements-dev.txt
@zsol [requested](https://github.com/Instagram/LibCST/issues/574#issuecomment-1006397621) I add [slotscheck](https://github.com/ariebovenberg/slotscheck) to the CI. 
Slotscheck prevents mistakes in `__slots__` from creeping in again. Fixing slots in #605 resulted in big memory savings.
Instructions for pre-commit are documented [here](https://slotscheck.readthedocs.io/en/latest/advanced.html#pre-commit-hook).
I've added `slotscheck` to the github build action. Let me know if you'd like it mentioned in `CONTRIBUTING.md` or `README.rst`
fixes #574
> add slotscheck to CI

- libcst/codemod/commands/convert_type_comments.py
- libcst/codemod/commands/tests/test_convert_type_comments.py
We have to parse code using the ast module in two situations, and in either case we can hit parse errors even though the code is valid python.
(a) by parsing with `type_comments=True` to reliably extract string type comments from code. This can throw errors if there are comments of the form `# type: something` anywhere where type information is invalid according to PEP 484.
(b) by parsing the type comments themselves into expressions or ast.FunctionType values. This can throw errors, even if (a) succeeds, whenever the type itself is not well-formed.
This commit updates `convert_type_comments` to handle these situations by ignoring type information on a specific node - prior to this commit, the entire codemod would have crashed, but there may be many other type comments in the module which …
> Handle ast.parse failures when converting function type comments

- libcst/codemod/commands/convert_type_comments.py
- libcst/codemod/commands/tests/test_convert_type_comments.py
My first time testing this codemod against a good-size project, I ran into a problem: the `Param` node can happen under either `FunctionDef` or `Lambda`, which I hadn't realized and I was assuming all `Param` transforms could rely on the surrounding `FunctionDef` for context information.
Since type comments cannot occur inside of Lambda (because all type comments are on statements, which cannot exist in lambdas), this is very easy to work around: just return false from visit_Lambda to truncate traversal of the cst.
I added a test case, which is a simplified example of actual code that caused me problems. I also verified that the codemod worked after this fix.
> Do not traverse lambdas - they can have Params but there are no type comments

- libcst/_nodes/tests/test_tuple.py
- native/libcst/src/parser/grammar.rs
Resolves #623
Added 2 tests, which fail with the current `main` but pass with this patch.
> [native] Don't redundantly nest StarredElement inside another Element

- libcst/_nodes/tests/test_atom.py
- native/libcst/src/parser/grammar.rs
Fixes #620
Add a bunch of tests to ensure this problem is fixed.
> [native] Allow unparenthesized tuples inside f-strings

- libcst/_nodes/statement.py
- libcst/_nodes/tests/test_match.py
Fixes #627. This check seems like preventing something that is allowed in the regular Python.
Added a test which didn't work before this patch.
> Don't require whitespace right after match

- libcst/_nodes/statement.py
- libcst/_nodes/tests/test_match.py
This patch adds support for proxying the right parentheses to the underlying child node, so it would be consistent with the left one. Resolves #625.
Added a test about a case that was broken before.
> Proxy both parentheses in some pattern matching nodes

- libcst/codemod/commands/convert_type_comments.py
- libcst/codemod/commands/tests/test_convert_type_comments.py
PEP 484 doesn't really specify carefully how function type
comments should work on methods, but since usually the type of
`self` / `cls` is automatic, most use cases choose to only annotate
the other arguments.
As a result, this commit modifies our codemod so that non-static
methods can specify either all the arguments, or all but one of
them. We'll correctly zip together the inline and func-type-comment
types either way, typically getting no type for `cls` or `self`.
We accomplish this by using matchers to trigger the visit
method for FunctionDef rather than using visit_FunctionDef, which gives
us enough context to determine when a function def is a regular
function versus a method (plus also matching the decorators against
`@staticmethod`, so that we trigger the normal function logic in …
> Add support for methods with func type comment excluding self/cls

- libcst/codemod/visitors/_apply_type_annotations.py
I find it difficult sometimes to read method and function signatures
when there are multiple arguments with type annotations - left-aligning
the arguments makes it much easier for me to skim and see, using mostly
my automatic visual resoning,
- the argument names
- the argument types
- the return type
Without this, I feel like I'm trying to run a parser in my head, which
is not as fast and distracts me from code-skimming.
This change was generated using thte new AddTrailingCommas codemod
(see #643) via the command
```
python -m libcst.tool codemod add_trailing_commas.AddTrailingCommas ./libcst/codemod/visitors/_apply_type_annotations.py
```
Wait for CI - this is pure formatting, a format-only change should be very safe
> Autoformat ApplyTypeAnnotationsVisitor

- libcst/codemod/commands/convert_type_comments.py
- libcst/codemod/commands/tests/test_convert_type_comments.py
The motivation for this is pytorch, where type comments mostly are maintained and it is
better to avoid quotes in methods that have jit compiler decorators.
I added a new test case verifying that the flag is properly propagated for all node types
that we would transform. Tests pass.
> Apply Type Comments: Allow for skipping quotes when applying type comments

- libcst/codemod/visitors/_apply_type_annotations.py
- Deduplicate some code for storing type information by extracting an Annotations dataclass.
- Rename several function to be more descriptive
- Add some docstrings
Run unit tests. There's no logic change here.
> Clean up ApplyTypeAnnotationsVisitor

- libcst/codemod/commands/convert_type_comments.py
It's nice to have a doc in general, and it's particularly nice to document in the cli help
that we have to use `--job=1` to avoid `ast` crashing.
Unfortunately our docs printer deletes formatting but it's still better than nothing.
```
> python -m libcst.tool codemod --no-format --jobs=1 convert_type_comments.ConvertTypeComments --help
usage: libcst.tool codemod [-h] [-j JOBS] [-p VERSION] [-u [CONTEXT]] [--include-generated] [--include-stubs] [--no-format] [--show-successes] [--hide-generated-warnings] [--hide-blacklisted-warnings] [--hide-progress] [--no-quote-annotations] COMMAND PATH [PATH ...]
Codemod that converts type comments into Python 3.6+ style annotations. Notes: - This transform requires using the `ast` module, which is not compatible with multiprocessing. So you should run …
```
> Add a DESCRIPTION to ApplyTypeComments

- .github/workflows/build.yml
I had a copy-paste error in add_trailing_commas.py.
I'll fix it in a follow-up PR, but first I want to make sure we can make CI fail so that this doesn't go unnoticed again.
Wait for github actions - if lint fails, this change is good.
> Add a check for copyright headers to lint stage

- libcst/codemod/commands/add_trailing_commas.py
I had a copy-paste error.
We now check headers in the lint stage, so as soon as that comes back clean we are good (I also did run the check locally, but I want to see CI working end-to-end before merging).
> Fix the copyright heading on add_trailing_commas.py

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
Because it isn't feasible to continuously push new releases of LibCST, we vendored a copy of
_apply_type_annotations.py into the pyre codebase so that we could rapidly improve `pyre infer`.
But as a result several bugfixes have wound up in pyre that belong here. This commit closes the
gap.
Each commit is either:
- a test harness commit, setting up (undesirable) test results that we'll fix in the next, or
- a port from a change made to pyre, whose commit message points to the original commit
```
> python -m unittest libcst.codemod.visitors.tests.test_apply_type_annotations
.....................................................................
Ran 69 tests in 7.039s
OK
```
> Port pyre fixes

- libcst/codemod/visitors/_apply_type_annotations.py
This is pretty trivial - the goal is to prevent lint errors when we vendor this into pyre.
> Remove trailing comment line from LICENSE header

- libcst/codemod/visitors/_apply_type_annotations.py
I'm still trying to get the code to pass all lints when we vendor it into pyre; the checks are slightly less picky about formatting in LibCST.
```
./check_copyright.sh
```
passes
> Tweak the license format again.

- libcst/codemod/visitors/__init__.py
- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/_gather_global_names.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_gather_global_names.py
Having a global name gatherer available helps us determine which names are in or out of scope when applying annotations.  This is similar to how we are currently using the import gatherer visitor in a pass prior to applying annotations, but that gatherer seems to have use cases perhaps beyond typing codemods - having a stand alone one for names seemed appropriate. 
Ideally we'd like to have better tracking for which names are in/out of scope that combines imports and globals/classes, which we could use in the apply type annotations codemod visitor to compare qualified names against. For now, having global names pre-calculated lets us determine whether or not a name in an annotation is a forward reference by checking if it's a name defined in the current module that we haven't yet seen …
> Define gather global names visitor

- libcst/codemod/visitors/tests/test_apply_type_annotations.py
This diff is because I realized one of the examples used `pass` in a stub, which is a recipe for confusion about which input is the stub versus the code (the order is stub, code_before, code_after).
Always using ... makes it a little clearer.
More importantly, I want to trigger a CI run because we have mystery failures (black exiting with code 1) on another PR, and I want to see if this commit triggers the same problems.
> Always use ... in stubs, not pass

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
Preserves the aliased import name when merging in annotations like
```
from foo import A as B
def f(x: B): ...
```
Fixes #661
> Preserve as-imports when merging type annotations.

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
resolves https://github.com/Instagram/LibCST/issues/656
python -m unittest libcst.metadata.tests.test_scope_provider.ScopeProviderTest.test_get_qualified_names_for_the_same_prefix
> fix qualified name get bug

- libcst/_parser/tests/test_parse_errors.py
- native/libcst/src/parser/errors.rs
The `ParserError` raised from the peg parser has 0-based line indices, but its `__str__` implementation expects it to be 1-based. This causes exceptions while trying to render the `ParserError` exception.
Fixes #678.
Added tests to verify `str()` doesn't blow up.
> [native] make sure ParserError's line is zero-indexed

- setup.py
Add two links to the sidebar on PyPI, to make it easier for folks to jump to the relevant pages. Example: https://pypi.org/project/django-htmx/ (PyPI adds the icons based on the link names).
You'll see them on next release.
> Add package links to PyPI

- native/libcst/src/tokenizer/core/mod.rs
- native/libcst/src/tokenizer/tests.rs
In Python it's allowed to escape `'` and `"` even in raw strings using `\`. This PR makes the tokenizer accept these strings.
Fixes #668.
Added unit tests.
> Tokenize escaped quotes in raw f-strings correctly

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
This is a performance fix for a change I made to correct compute qualified names in #682
I hacked three versions of the `node_accesses` set creation in `Scope.get_qualified_names_for` and ran a perf test on them:
```
(libcstvenv) lpetre@lpetre-mbp LibCST % cat /tmp/fastero.json 
{
"setup": "from libcst import safe_parse_module, MetadataWrapper; from libcst.metadata import QualifiedNameProvider; import os; from wcmatch import wcmatch; env = os.environ; paths = list(wcmatch.WcMatch('/Users/lpetre/dev/src/github.com/python/cpython/Lib', '*.py', exclude_pattern='tests|test', flags=wcmatch.RECURSIVE).imatch()); paths = paths[:100]; mods = [MetadataWrapper(safe_parse_module(open(path).read())) for path in paths];",
"results": [
{
"snippet_name": "0.4.2",
"snippet_code": "env['FIX_QNAME'] = …
```
> Fix slow qualified name perf in 0.4.2+

- libcst/_nodes/expression.py
- libcst/_nodes/tests/test_simple_string.py
Fix https://github.com/Instagram/LibCST/issues/636
```
>>> from libcst import *
>>> m = parse_module('''""""foo"""''')
>>> m.body[0].body[0].value.raw_value
File "<stdin>", line 1, in <module>
File "C:\Users\zsolz\projects\libcst\libcst\_nodes\expression.py", line 682, in raw_value
quote_len = len(self.quote)
File "C:\Users\zsolz\projects\libcst\libcst\_nodes\expression.py", line 666, in quote
raise Exception("Invalid string {self.value}")
Exception: Invalid string {self.value}
```
1. Unit test
2. Manual test
```
>>> from libcst import *
>>> m = parse_module('''""""foo"""''')
>>> m.body[0].body[0].value.raw_value
'"foo'
```
> expression: fix SimpleString's quote method

- libcst/codemod/commands/convert_type_comments.py
- libcst/codemod/commands/tests/test_convert_type_comments.py
Prior to this PR convert_type_comments codemod stripped any comments following a type comment. So, for example,
y = 5  # type: int  # foo
was converted to
y: int = 5
instead of
y: int = 5  # foo
The PR changes the codemod to preserve any such comments.
Added a new test case.
> convert_type_comments now preserves comments following type comments

- libcst/metadata/scope_provider.py
We don't need to recompute this name prefix every time we try to lookup a qualified name for a node. This value is immutable when the scope is constructed.
There is a certain type of file that causes the scope provider to take an extraordinary amount of time.
These files tend to fit a specific pattern:
- very long and machine generated
- access and assignment to the same variable repeatedly in the same scope
Here is an example: https://github.com/FreeOpcUa/python-opcua/blob/0.98.11/opcua/server/standard_address_space/standard_address_space_part9.py
I've been running these w/ yappi to figure out where the scope provider might be improved.
Previously this file would take ~70 seconds on my laptop (Apple M1 Pro, 32GB RAM). Now it takes ~30 seconds. 
Here is the top hits from yappi (sorted by …
> Cache the scope name prefix to prevent scope traversal in a tight loop

- native/libcst/src/nodes/expression.rs
- native/libcst/tests/fixtures/tuple_shenanigans.py
Review stack (1/2) [Next](https://github.com/Instagram/LibCST/pull/713)
* #712
* #713
----
Don't drop rpars from empty tuples during inflate. In fact that elements check isn't necessary anymore, since inflation happens separately from parsing now: the whitespace between an empty pair of parenthesis has already been consumed during lpar inflation.
Fixes #711.
Added roundtrip tests.
> Fix parsing of parenthesized empty tuples

- libcst/_nodes/expression.py
- libcst/_nodes/tests/test_funcdef.py
- libcst/_nodes/tests/test_lambda.py
- libcst/_typed_visitor.py
- libcst/matchers/__init__.py
- native/libcst/src/nodes/expression.rs
- native/libcst/src/parser/grammar.rs
- native/libcst/tests/fixtures/fun_with_func_defs.py
- native/libcst/tests/fixtures/tuple_shenanigans.py
Review stack (2/2) [Prev](https://github.com/Instagram/LibCST/pull/712)
* #712
* #713
----
This PR introduces a new `whitespace_after` field to `ParamSlash` to represent whitespace after the `/` in signatures. Parsing for this new field is implemented in the native parser (enabled with `LIBCST_PARSER_TYPE=native` env var currently), but not the old pure python one.
Fixes #679.
Added roundtrip and unit tests.
> Support whitespace after ParamSlash

- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst/src/parser/errors.rs
> bump rust dependencies

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
This prefix matching logic assumed there is always a '.' in the string, that is incorrect.
We noticed after releasing that a codemod is trying to insert new symbols and using `ScopeProvider.get_qualified_names_for` w/ the new name to prevent collisions.
See the new test for an example of how this would break.
python -m unittest libcst.metadata.tests.test_scope_provider.ScopeProviderTest.test_prefix_match
> Fix get_qualified_names_for matching on prefixes of the given name

- libcst/_parser/conversions/expression.py
TLDR:
* Fixed a `missing 'f' for f-string` issue.
* Tried to fix the issue by creating a codemod, but my solution has many false positives, so it is not included in this PR code changes.
When I was working on another PR (#704), I encountered a `missing 'f' for f-string` issue ([code link](https://github.com/Instagram/LibCST/pull/704/files#diff-556d83ff3f2718b09556ff7002e044ff03e255423ffe269220a0c316256d2d7bL666)). I was wondering if I can write a codemod command to solve this automatically. Below code is my first attempt to solve this issue, it can find the `missing 'f' for f-string` typos, but it has many false positives and I realized it's not simple problem as I thought. 
This PR is to fix the found `missing 'f' for f-string` issue and also to see if you have tried to solve this issue …
> Fix parse error message for number parsing

- requirements-dev.txt
flake8 5.0 breaks the fixit compatibility layer, see https://github.com/Instagram/Fixit/issues/222
CI
> pin flake8 below 5.0

- .readthedocs.yml
This pull request should fix #725.
The reason we should choose the [`graphviz` package](https://packages.ubuntu.com/jammy/graphviz), instead of other packages whose package names also contain the `graphviz` keywords, is because it's [officially endorsed](https://graphviz.org/download/#linux).
> Fix problematic doc build, due to the new builder image provided by readthedocs doesn't has the `graphviz-dev` package pre-installed any more

- libcst/metadata/full_repo_manager.py
This pull request should fix #749.
> Fix docstring of `FullRepoManager`

- docs/source/conf.py
- requirements-dev.txt
This pull request should fix #747.
I have tried to build document of LibCST with Sphinx 5.1.1 locally. It works fine and smoothly. The only trivial change we need to make to accommodate is to specify the `language` setting to non-`None` value in `conf.py`.
> Update Sphinx to 5.1.1

- .github/workflows/ci.yml
There are no available binary wheels for lxml for Windows & Python 3.11 yet:
https://bugs.launchpad.net/lxml/+bug/1977998
Until that's resolved, let's skip tests in this configuration.
> Skip CI checks on Python 3.11 x Windows

- libcst/matchers/_matcher_base.py
- libcst/matchers/tests/test_matchers.py
This PR should fix #528.
I also added unit test, to prevent regression.
> Fix bug when `TypeOf` is one of options in `OneOf` / `AllOf`

- libcst/matchers/_matcher_base.py
- libcst/matchers/tests/test_findall.py
- libcst/matchers/tests/test_matchers_with_metadata.py
I also tuned the related unit test to accommodate this change.
This PR closes #526.
> Raise informative exception when metadata is unresolved in a metadata-based match

- README.rst
We have been showing the wrong badge, which shows the build status of the `pip` library, instead of the `LibCST` library.
> Use the correct doc build status badge

- libcst/codemod/tests/test_codemod_cli.py
- libcst/tool.py
This PR tries to fix the bug manifesting in #769. In summary, we specify that the black formatter should use the same target Python version which libcst itself uses.
> Fix the bug that the use of formatter in codemods has undetermined target Python version, resulting in hard-to-reason-with behavior

- libcst/_parser/entrypoints.py
- libcst/_parser/tests/test_parse_errors.py
- libcst/_typed_visitor.py
- libcst/_typed_visitor_base.py
- libcst/codegen/gather.py
- libcst/codegen/gen_matcher_classes.py
- libcst/codegen/gen_type_mapping.py
- libcst/codegen/gen_visitor_functions.py
- libcst/codemod/_cli.py
- libcst/matchers/_decorators.py
- libcst/matchers/_matcher_base.py
Summary of changes:
1. Remove the unnecessary overhead of copying singleton objects.
2. Avoid generating unnecessary `pass` statements.
3. Remove the unnecessary cost of building intermediate lists.
4. Remove an unused import, an overlook from commit 8e6bf9e9.
5. Simplify an invocation of `Mapping.get()`.
6. Just use unittest's `assertRaises()` to specify expected exception types, instead of catching every possible `Exception`s, which could suppress legitimate errors and hide bugs
7. Several other small refactors.
> Several trivial refactors

- libcst/metadata/__init__.py
- libcst/metadata/accessor_provider.py
- libcst/metadata/tests/test_accessor_provider.py
Adding a provider which can tell what accessor to use to go from the parent to that child node
I want to be able to see what accessor needs to be used to go from the parent to the given child
> Add AccessorProvider

- .github/workflows/build.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
CI
> [ci] Remove deprecated ::set-output directive

- libcst/matchers/_visitors.py
- libcst/matchers/tests/test_decorators.py
This fixes the bug that #429 was intended to fix. Unfortunately the name checked for in that PR (`types.Union`) is not what was actually merged in Python 3.10 (`types.UnionType`) so that fix is not effective in 3.10. Here we instead use an `isinstance` check against the real imported `types.UnionType` (with fallback for earlier Python versions). And update the test to use a real PEP 604 union (skipping on Python versions before 3.10) for better fidelity to reality than the mock that was previously used.
`python -m unittest libcst.matchers.tests.test_decorators` passes in both a 3.8 and a 3.10 virtualenv.
> fix PEP 604 union annotations in decorators

- libcst/codemod/visitors/_add_imports.py
- libcst/codemod/visitors/tests/test_add_imports.py
Refer https://github.com/Instagram/LibCST/pull/343#issuecomment-1367622138
Instead of checking for docstring for all the elements of the body, this PR only keeps the check for the 0th element since our objective is to only honor the module docstrings.
The reason I am asking for this, I found a case in one of the repositories where the docstrings were written outside the function like how we have in Java, obviously, this is unconventional and unpythonic, but my only concern is why are we checking for docstrings which are not module docstrings?
Consider a case
```
from __future__ import annotations
from __future__ import division
import abc
from xyz import def
"""Some docstring"""
def some_func():
pass
```    
Let's say we are trying to add an import `from typing import List`, the final …
> [AddImportsVisitor] Docstring Check Only for the Top Element of the Body

- native/libcst/src/parser/grammar.rs
- native/libcst/tests/fixtures/with_wickedness.py
Fixes #855 
When we added support for parenthesized with statements, the grammar on the with itself was correct (it's a right and left parenthesis around a comma-separated list of with-items, with a possible trailing comma).
But inside of the "as" variation of the with_item rule we have a peek at the next character, which was allowing for a comma or a colon. That peek needs to also accept right parentheses - otherwise, if the last item contains an `as` and has no trailing comma we fail to parse.
The bug is exercisecd by, for example, this code snippet:
```
with (foo, bar as bar,):
pass
```
The with_wickedness test fixture has been revised to include both the plain and async variations of this example snippet with and without trailing comma, and tests pass after the peek rule fix.
```
cd …
```
> Fix Github issue 855 - fail to parse with statement

- .gitignore
Adds `venv/` and `.venv/` to the gitignore list, so that common
virtualenv names aren't seen as changes to commit.
Created virtualenv named `venv`; `git status` was clean.
> Ignore common virtualenv names

- libcst/_types.py
- libcst/helpers/module.py
- libcst/metadata/full_repo_manager.py
- libcst/metadata/name_provider.py
- libcst/metadata/tests/test_name_provider.py
This allows FullyQualifiedNameProvider to work with absolute paths,
rather than assuming all paths given will be relative to the current
directory. This enables tools like Fixit to provide a root path, and
have the FullyQualifiedNameProvider correctly scope the final results
relative to that root path.
This does require that both the root path and the given file paths
match the other as relative or absolute, due to the
`calculate_module_and_package` helper comparing file paths relative
to the root path, but this seems like a reasonable tradeoff, and
unlikely to cause a problem in normal use cases.
Updated test cases. Works with in-progress Fixit2 changes.
> Pass root path to FullyQualifiedNameProvider

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/pypi_upload.yml
With the latest setup-python actions, there is a better caching
mechanism available that also requires less setup, and provides better
fallback behavior that should help avoid the random CI failures that
have been happening on 3.11 for setuptools-rust. This ensures that we
install the necessary dependencies before attempting to build the
package or run tests, while still enabling speedups in best case
scenario when requirements files haven't changed.
See the upstream readme for details:
https://github.com/actions/setup-python#caching-packages-dependencies
CI
> Use new setup-python caching actions

- .github/workflows/build.yml
- .github/workflows/pypi_upload.yml
[ci] Fix pypi_upload workflow
pypi_upload has been broken since #810, because `actions/checkout` defaults to a shallow checkout that only checks out the revision triggering the workflow. This causes setuptools-scm to miss the most recent tag, causing the version to be detected as `0.1`.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Instagram/LibCST/pull/889).
* #890
* __->__ #889
> [ci] Fix pypi_upload workflow

- docs/source/metadata.rst
- libcst/helpers/paths.py
- libcst/helpers/tests/test_paths.py
- libcst/metadata/__init__.py
- libcst/metadata/file_path_provider.py
- libcst/metadata/tests/test_file_path_provider.py
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #892
Caches file path information on the root `Module` node.
Resolves paths when caching, so they are always absolute paths.
Adds a new `chdir` helper to change working directory and automatically
revert to previous directory, which makes testing file paths with the
`"."` repo root easier.
> Add new FilePathProvider

- libcst/helpers/module.py
- libcst/helpers/tests/test_module.py
When we resolve a relative import from root package "", we get the import prefixed by "."
However, this kind of imports are not allowed and cpython throws an error:
```
/Users/michaelpo/PycharmProjects/pythonProject/venv/bin/python /Users/michaelpo/PycharmProjects/pythonProject/main.py 
File "/Users/michaelpo/PycharmProjects/pythonProject/main.py", line 2, in <module>
from .l1 import l1_func
ImportError: attempted relative import with no known parent package
Process finished with exit code 1
```
Unit tests
> Fix: relative imports from '' package are not allowed

- libcst/codegen/generate.py
- libcst/codemod/tests/test_codemod_cli.py
One spot used `python`, the other used `python3` – `sys.executable` is known to be correct.
> Ensure current Python interpreter is used for subprocesses

- libcst/codemod/tests/test_codemod_cli.py
- libcst/tool.py
This enables codemodding things by just plonking a CodemodCommand class into any old importable module and running `python -m libcst.tool codemod -x some_module.SomeClass ...`
> Allow running codemods without configuring in YAML

- libcst/_nodes/expression.py
- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
* Fixes an issue where ApplyTypeAnnotationsVisitor would crash on code like `SomeClass.some_attribute = 42` with a "Name is not a valid identifier" error message.
* Changes the above-mentioned error message to include the bad name in the message, for easier debugging.
* Adds tests for all valid assignment targets, as described here: https://libcst.readthedocs.io/en/latest/nodes.html#libcst.BaseAssignTargetExpression.
Context: I'm trying to fix https://github.com/google/pytype/issues/1402.
> Fix ApplyTypeAnnotationsVisitor behavior on attribute assignments.

- libcst/_nodes/statement.py
- libcst/_nodes/tests/test_funcdef.py
- libcst/matchers/__init__.py
relax validation on decorators
> relax validation rules on decorators

- .github/workflows/ci.yml
- CHANGELOG.md
- libcst/_parser/entrypoints.py
- native/libcst/README.md
The old parser is now only available using LIBCST_PARSER_TYPE=pure
> Switch default parser implementation to native

- libcst/_nodes/expression.py
- libcst/_nodes/statement.py
- libcst/codegen/gen_matcher_classes.py
- libcst/codemod/commands/strip_strings_from_types.py
- libcst/codemod/visitors/_gather_exports.py
This can return bytes if the string is a bytestring, e.g.:
In [1]: import libcst as cst
In [2]: cst.parse_expression('b"foo"').evaluated_value
Out[2]: b'foo'
> Fix type of `evaluated_value` on string to allow bytes

- .editorconfig
Neovim keeps throwing an error of being unable to parse `charset`, and upon checking https://editorconfig.org/ it indeed does seem correct not to have quotes around the value.
> remove quotes around charset in .editorconfig

- libcst/codemod/visitors/_apply_type_annotations.py
- libcst/codemod/visitors/tests/test_apply_type_annotations.py
Tracks applied annotations so that we only annotate any given variable in a scope the first time it is assigned.
Fixes #955
> Do not annotate the same variable multiple times in ApplyTypeAnnotationsVisitor

- libcst/codemod/commands/rename.py
- libcst/codemod/commands/tests/test_rename.py
When renaming within the same module (i.e. `logging.warn -> logging.warning`), make sure the codemod doesn't insert an extra `import logging` statement.
> codemod/rename: Avoid duplicating import statements when the module name doesn't change

- libcst/codemod/_cli.py
- libcst/tests/test_e2e.py
`codemod.gather_files` should not try to gather dirs those names ending with .py, only regular files
(the issue encountered in an actual codebase).
libcst/tests/test_e2e.py updated
> Don't gather dirs ending .py

- .github/workflows/ci.yml
- libcst/_add_slots.py
- pyproject.toml
> drop support for Python 3.7

- .github/workflows/ci.yml
- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst/benches/parser_benchmark.rs
criterion-cycles-per-byte is not supported on non-x86_64 platforms, so `cargo test` cannot be run:
```
❯ cargo test
Compiling libcst v0.1.0 (x)
Compiling criterion-cycles-per-byte v0.1.2
error: criterion-cycles-per-byte currently relies on x86 or x86_64.
--> /Users/tom/.config/cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-cycles-per-byte-0.1.2/src/lib.rs:34:1
|
34 | compile_error!("criterion-cycles-per-byte currently relies on x86 or x86_64.");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
This PR makes it conditional and allows the tests to run.
> Remove criterion-cycles-per-byte dependency and related benchmark measurement

- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst/benches/parser_benchmark.rs
- native/libcst/src/parser/numbers.rs
- native/libcst/src/tokenizer/core/mod.rs
- native/libcst/src/tokenizer/operators.rs
- native/libcst/src/tokenizer/text_position/mod.rs
- native/libcst/src/tokenizer/whitespace_parser.rs
Fixes #986. This is also rebased on top of https://github.com/Instagram/LibCST/pull/995 to allow me to run the benchmarks.
When calling `libcst_native::parse_module` from multiple threads the parsing performance drops dramatically. This is somewhat documented [in the regex_automata crate](https://docs.rs/regex-automata/latest/regex_automata/) and in other places around the internet:
> You need to work-around contention issues with sharing a regex across multiple threads. The meta::Regex::search_with API permits bypassing any kind of synchronization at all by requiring the caller to provide the mutable scratch spaced needed during a search.
I've added a multi-threaded benchmark using Rayon. The use of thread locals improves the throughput by 22% and reduces the time by 18%:
``` …
```
> Switch to using thread_local regular expressions to stop mutext contention

- native/libcst/src/tokenizer/text_position/mod.rs
Remove need for regex in TextPosition::matches
> Remove need for regex in TextPosition::matches

- native/libcst/src/tokenizer/whitespace_parser.rs
parser: remove Regexes from whitespace parser
removing Regexes from whitespace parser allows ditching of thread local storage + lazy initialization cost
This shows a modest 2% improvement in overall parse time (inflate is improved by 10%)
> parser: remove Regexes from whitespace parser

- libcst/metadata/scope_provider.py
scope_provider: Simplify parent resolution
This PR introduces `Scope._next_visible_parent` which deduplicates much of the logic between `_contains_in_self_or_parent`, `_find_assignment_target_parent`, and `_getitem_from_self_or_parent`.
This will be helpful when implementing scope resolution for the future `AnnotationScope`.
There should be no functionality change.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Instagram/LibCST/pull/1013).
* #1014
* __->__ #1013
> scope_provider: Simplify parent resolution

- libcst/helpers/common.py
- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Scope provider changes for type annotations
> Scope provider changes for type annotations

- libcst/codemod/visitors/_add_imports.py
- libcst/codemod/visitors/_gather_imports.py
- libcst/codemod/visitors/tests/test_add_imports.py
Proposed fix for #1023. It changes `AddImportsVisitor` so it only considers adding new imports after/at the first import block before any other statements, if any.
Added a few tests to `test_add_imports.py`
> AddImportsVisitor: add imports before the first non-import statement

- libcst/metadata/scope_provider.py
- libcst/metadata/tests/test_scope_provider.py
Fixes #1018 by making all calls to `_NameUtil.get_name_for()` use `get_full_name_for_node()` instead.
> ScopeProvider: Record Access for Attributes and Decorators

- native/libcst/src/tokenizer/core/mod.rs
- native/libcst/src/tokenizer/tests.rs
- native/libcst/tests/fixtures/super_strings.py
PEP 701 relaxed restrictions on f-string grammar significantly. LibCST's parser already supported these changes, but the tokenizer had a severe bug related to nested f-strings. This PR fixes that.
Fixes #993.
Added test cases
> Parse arbitrarily nested f-strings

- native/libcst/src/tokenizer/core/mod.rs
- native/libcst/src/tokenizer/core/string_types.rs
- native/libcst/tests/fixtures/super_strings.py
PEP 701 relaxed the rules around f-strings. This PR updates the tokenizer to support multiline expressions in f-strings always (regardless of triple quotes). Fixes #989.
Added test cases
> Parse multiline expressions in f-strings

- CHANGELOG.md
- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst_derive/Cargo.toml
> bump version to 1.1.0

- libcst/metadata/file_path_provider.py
The file path provider claims it provides a [collection of paths](https://github.com/Instagram/LibCST/blob/7ca5d7f1736c38b27dcdd41243343f2e2b5e1eb1/libcst/metadata/file_path_provider.py#L13) but in reality it provides a [single path](https://github.com/Instagram/LibCST/blob/7ca5d7f1736c38b27dcdd41243343f2e2b5e1eb1/libcst/metadata/file_path_provider.py#L45). This is a hole because gen_cache doesn't have great type annotations: [example](https://github.com/Instagram/LibCST/blob/7cb229d175b79cbf392a34ecb58e79686c73a82d/libcst/metadata/base_provider.py#L62).
CI
> fix filepathprovider generic type

- pyproject.toml
Add 3.12 classifier and update description to correctly reflect supported Python versions
> Update pyproject.toml for Python 3.12 support

- .flake8
- pyproject.toml
> upgrade flake8

- native/Cargo.lock
- native/libcst_derive/Cargo.toml
- native/libcst_derive/src/cstnode.rs
- native/libcst_derive/src/into_py.rs
Release notes: https://github.com/dtolnay/syn/releases/tag/2.0.0
> Update syn to v2

- .github/workflows/ci.yml
ci: update rust toolchain GHA
`actions-rs` is unmaintained
> ci: update rust toolchain GHA

- .github/workflows/build.yml
- .github/workflows/ci.yml
> cI: remove rust cache

- .gitignore
- apt.txt
when we switch to the rust compiler by default, mybinder stop working, as reported in https://github.com/Instagram/LibCST/issues/1054 this is because the binder docker image does not have a rust compiler or tools, this install them by using the apt.txt file
if you go to https://mybinder.org/v2/gh/aleivag/LibCST/fix-binder?filepath=docs/source/tutorial.ipynb you'll see this works
> installing rustc/cargo for mybinder demo

- .github/workflows/build.yml
- .github/workflows/pypi_upload.yml
v4 of upload-artifacts have changed its behavior: artifacts can no longer be mutated after they're uploaded.
This PR creates a separate artifact per build job
> ci: use separate artifact names

- native/libcst/src/nodes/expression.rs
The `Codegen` trait is `pub`, but users wanting to explicitly perform codegen for `Element` had to copy-paste this part of the code.
(See also D52275507.)
> Allow `Element::codegen` to be used by external users

- .readthedocs.yml
- pyproject.toml
Readthedocs builds are currently failing because the libcst wheel fails
to build, hitting an error when trying to get rust dependencies:
```
running build_rust
Updating crates.io index
error: failed to select a version for the requirement `regex = "=1.9.3"`
candidate versions found which didn't match: 1.8.4, 1.8.3, 1.8.2, ...
location searched: crates.io index
required by package `libcst v1.1.0 (/home/docs/checkouts/readthedocs.org/user_builds/libcst/checkouts/latest/native/libcst)`
error: `cargo metadata --manifest-path native/libcst/Cargo.toml --format-version 1` failed with code 101
```
Assuming this is related to current configuration requesting rust v1.55,
rather than 1.70 that is currently offered.
Look at CI builds on RTD
> Upgrade rust to version 1.70 in readthedocs config

- libcst/_nodes/statement.py
- native/libcst/tests/fixtures/malicious_match.py
Fix parsing list matchers without explicit brackets
```
match a:
case 1, 2: pass
```
This is parsed correctly by the grammar, but the default values of `MatchList.lbracket` and `MatchList.rbracket` are inconsistent between Python and Rust, causing the above snippet to round-trip (from Python) to:
```
match a:
case [1, 2]: pass
```
Fixes #1096.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Instagram/LibCST/pull/1097).
* #1098
* __->__ #1097
> Fix parsing list matchers without explicit brackets

- libcst/_nodes/statement.py
- libcst/tests/test_roundtrip.py
- native/libcst/tests/fixtures/malicious_match.py
Add roundtrip tests from Python
Our current roundtrip tests only excerise the Rust codepaths. This PR runs the same roundtrip scenarios but from Python.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Instagram/LibCST/pull/1098).
* __->__ #1098
* #1097
> Add roundtrip tests from Python

- .github/workflows/build.yml
- .github/workflows/pypi_upload.yml
ci: build linux-arm64 wheels using emulation
Stop using self-hosted runner
> ci: build linux-arm64 wheels using emulation

- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst/src/nodes/traits.rs
Testing to see if this is as easy as it looks
> Upgrade pyo3 to 0.20

- docs/source/metadata.rst
✏️ Fix tiny typo in `docs/source/metadata.rst`
Docs only.
> ✏️ Fix tiny typo in `docs/source/metadata.rst`

- docs/source/scope_tutorial.ipynb
✏️ Fix typo in `docs/source/scope_tutorial.ipynb`
Only docs
> ✏️ Fix typo in `docs/source/scope_tutorial.ipynb`

- libcst/codemod/visitors/_gather_string_annotation_names.py
- libcst/codemod/visitors/tests/test_gather_string_annotation_names.py
`GatherNamesFromStringAnnotationsVisitor`, which is called by `GatherUnusedImportsVisitor`, which is called by `RemoveImportsVisitor`, attempts to parse any string contained in an annotation as if it were Python code. This behavior was added in https://github.com/Instagram/LibCST/pull/353 with the goal of parsing type names wrapped in strings.
However, not all strings occurring inside annotations can or should be interpreted that way. For example:
```python
from typing import Literal
a: Literal["in"]
b: list[Literal["1x"]]
c: Literal["Any"]
```
`a` and `b` will cause a `ParserSyntaxError`, while `c` will be incorrectly treated as a mention of the symbol `Any`.
This PR makes two changes to `GatherNamesFromStringAnnotationsVisitor`:
- Anything inside a `Literal` is ignored.
- This fixes all …
> Fix Literal parse error in RemoveImportsVisitor

- libcst/codemod/_cli.py
- libcst/tests/test_e2e.py
fix: don't reset context.scratch between files
#453 fixed scratch leaking between files by setting it to empty, but that drops all the scratch space that was set up before the codemod runs (e.g. in the transformer's constructor)
This PR improves the fix by preserving the initial scratch.
> fix: don't reset context.scratch between files

- .github/workflows/pypi_upload.yml
This PR removes the hardcoded access token for pypi from the workflow.
Run publishing to test.pypi.org in a non-final version of this PR.
> use trusted publishing for pypi

- libcst/helpers/module.py
- libcst/helpers/tests/test_module.py
- libcst/metadata/base_provider.py
- libcst/metadata/file_path_provider.py
- libcst/metadata/full_repo_manager.py
- libcst/metadata/name_provider.py
- libcst/metadata/tests/test_metadata_wrapper.py
- libcst/metadata/tests/test_name_provider.py
- libcst/metadata/type_inference_provider.py
When determining the module name and package for a source file, LibCST currently takes the file name relative to the repository root. With this change, it will instead look for the closest directory containing a `pyproject.toml` file in the file's ancestors, and consider the file name relative to that directory.
This gives correct module and package names when processing a repository containing multiple packages. For files that are not covered by a `pyproject.toml`, the search ends with the given repository root, thus retaining the old behavior.
> FullyQualifiedNameProvider: Optionally consider pyproject.toml files when determining a file's module name and package

- libcst/_nodes/statement.py
- libcst/tests/test_roundtrip.py
- native/libcst/tests/fixtures/malicious_match.py
fix various Match statement visitation errors
Fixes #1160.
This PR also
- fixes `whitespace_before_colon` being swallowed during visitation on `MatchCase`s
- adds a new type of roundtrip test that catches issues of this class: the test applies a noop transformer to exercise the visitation API and compares the result with the original source.
- adds a few more cases to the match fixture
> fix various Match statement visitation errors

- docs/source/codemods_tutorial.rst
After https://github.com/Instagram/LibCST/pull/879 got implemented, we can assume that most user codemods are loaded in this way instead of editing the LibCST source (it would be just pip installed). So `-x` flag is very important and should be mentioned in docs. 
I am open to suggestions on how to improve the wording and also mention the built-in codemods and `libcst.tool list` better.
#shipit (just docs)
> Mention codemod -x flag in docs

- libcst/tests/test_fuzz.py
- stubs/hypothesis.pyi
- stubs/hypothesmith.pyi
- stubs/setuptools.pyi
- stubs/typing_inspect.pyi
`# pyre-placeholder-stub` is a deprecated and non-standard-compliant feature in Pyre. This PR replaces it with the getattr-Any pattern and suppress all downstream type errors. 
`hatch run pyre`
> Remove uses of `# pyre-placeholder-stub`

- libcst/_nodes/statement.py
- libcst/_nodes/tests/test_if.py
Don't allow no space no parentheses after `if`.
There should be a validation for `If` node similar to others such as `While` or `Assert` to not allow generating incorrect code.
There is even a TODO left for that reason.
Let me know if there should be other validations for `If`.
With the current version of LibCST it is possible to generate the code like this with an `If` node followed by `Name('x')` without space:
```python
ifx:
pass
```
which isn't correct Syntax. 
The new test fails:
```python
======================================================================
FAIL: test_invalid_0 (libcst._nodes.tests.test_if.IfTest.test_invalid_0)
File "libcst\testing\utils.py", line 88, in …
```
> Add validation for If node

- .github/workflows/ci.yml
- README.rst
- codecov.yml
- pyproject.toml
Codecov keeps failing in CI. Chatted with @zsol and it doesn't seem worth the effort.
CI should actually pass.
> Drop codecov from CI and readme

- libcst/codemod/tests/test_codemod_cli.py
- libcst/matchers/_visitors.py
Support matcher decorators with multiprocessing on Windows/macOS.
See issue #1181 for more context.
- Call `_gather_matchers` later in the code (first time when it's needed) to ensure we initialize them in a process AFTER the "fork".
- Proactively check if attributes are not properties instead of trying to evaluate them and suppressing all errors.
```
> hatch run python -m unittest libcst.codemod.tests.test_codemod_cli.TestCodemodCLI.test_matcher_decorators_multiprocessing
FAILED (failures=1)
```
```
> hatch run python -m unittest libcst.codemod.tests.test_codemod_cli.TestCodemodCLI.test_matcher_decorators_multiprocessing     
.
Ran 1 test in 0.973s
OK
```
> fix certain matchers breaking under multiprocessing by initializing them late

- docs/source/conf.py
Fix doc build error
Apparently doc2path now returns a path not a string
> Fix doc build error

- .github/workflows/build.yml
Allow CIBW to build wheels with -msullinux tags.
Alpine CIs could greatly benefit from having `libcst` available.
Closes #962
> Draft: ci: build wheels for musllinux

- .github/workflows/build.yml
See #1243. CI started failing after pulling that change into `main`.
This fixes current CI failures by skipping Musl builds for `i686`, `ppc64le`, `s390x`, and `armv7le` architectures.
The failures are due to Rust ecosystem having only partial support / not having tool chains for these architectures. For the list of supported archs and tiers of support, see:
https://doc.rust-lang.org/nightly/rustc/platform-support.html
The architectures skipped here are either, from the Rust PoV:
- Tier-2 support without host tools.
- Tier-3 support without host tools.
> ci: skip musllinux builds for unsupported archs

- libcst/codemod/commands/rename.py
This PR changes RenameCodemod to store its per-module state in `self.context.scratch` which gets properly reset between files.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Instagram/LibCST/pull/1250).
* #1251
* __->__ #1250
> rename: store state in scratch

- libcst/codemod/commands/rename.py
- libcst/codemod/commands/tests/test_rename.py
When requesting a rename for `a.b.c`, we want to act on `import a` when it's used to access `a.b.c`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Instagram/LibCST/pull/1251).
* #1252
* __->__ #1251
* #1250
> rename: handle imports via a parent module

- libcst/codemod/commands/rename.py
- libcst/codemod/commands/tests/test_rename.py
When renaming `a.b` -> `c.d`, in imports like `import a.b as x` the as_name wasn't correctly removed even though references to `x` were renamed to `c.d`.
This PR makes the codemod remove the `x` asname in these cases.
> rename: Fix imports with aliases

- libcst/codemod/commands/rename.py
refactor: allow scheduled_removals to accept a tuple
This fixes a TODO
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Instagram/LibCST/pull/1253).
* #1254
* __->__ #1253
> refactor: allow scheduled_removals to accept a tuple

- libcst/codemod/commands/rename.py
- libcst/codemod/commands/tests/test_rename.py
#1254 was a bit too aggressive in removing commas. They shouldn't be removed if there are parenthesis around the imported names.
> rename: don't eat commas unnecessarily

- libcst/codemod/commands/rename.py
- libcst/codemod/commands/tests/test_rename.py
For toplevel module names imported via `import foo`, the rename codemod would fail to change these. This PR fixes that.
> rename: fix renaming toplevel names

- libcst/codemod/commands/convert_union_to_or.py
- libcst/codemod/commands/tests/test_convert_union_to_or.py
This codemod can help upgrade typing syntax to Python 3.10+ by converting unions to use `|` as specified in PEP604
hatch run python -m unittest libcst.codemod.commands.tests.test_convert_union_to_or
> Add codemod to convert `typing.Union` to `|`

- libcst/codemod/commands/fix_variadic_callable.py
- libcst/codemod/commands/tests/test_fix_variadic_callable.py
Very simple codemod that does one thing, which fixes a somewhat common mistake in type annotations:
`Callable[[...], T]` -> `Callable[..., T]`
hatch run python -m unittest libcst.codemod.commands.tests.test_fix_variadic_callable
> Add codemod to fix variadic callable annotations

- native/libcst/src/nodes/mod.rs
This PR re-exports a number of structs related to type aliases and type vars in the rust library. The use case for this is making it easier to traverse a parsed `Module`.
You can traverse `SmallStatement::TypeAlias(value) => value.type_parameters[0].param` all without directly referring to those types (ie: not needing to import them) but `TypeParam.param` is an enum. You can't do much with that without matching against the enum values to determine the actual type, which requires them to be imported.
Tested locally and was able to use the new exports.
> Expose TypeAlias and TypeVar related structs in rust library

- .github/workflows/build.yml
`cibuildwheel` fails to build these after a recent version upgrade
> ci: disable macos intel wheels

- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst/src/nodes/expression.rs
- native/libcst/src/nodes/parser_config.rs
- native/libcst/src/nodes/traits.rs
- native/libcst/src/parser/errors.rs
- native/libcst/src/py.rs
- native/libcst_derive/src/into_py.rs
This updates PyO3 to version 0.22, and adapt to the new APIs.
```
cd native && cargo test
```
> Upgrade pyo3 to 0.22

- libcst/codemod/commands/rename.py
- libcst/codemod/commands/rename_typing_generic_aliases.py
- libcst/codemod/commands/tests/test_rename.py
- libcst/codemod/commands/tests/test_rename_typing_generic_aliases.py
This PR adds a codemod for Python 3.9+ that updates references like `typing.List` to just `list`. It includes all the builtins that have an alias in the typing module.
We can also do the same thing for some non-builtin types in the collections module (the full list is in https://peps.python.org/pep-0585/#implementation) but I'm not sure if that should be a separate codemod or added to this one.
I also had to update the RenameCommand to avoid adding imports if the new name is a builtin.
hatch run python -m unittest libcst.codemod.commands.tests.test_rename
hatch run python -m unittest libcst.codemod.commands.tests.test_rename_typing_generic_aliases
> Add codemod to rename typing aliases of builtins

- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst/src/nodes/expression.rs
- native/libcst/src/nodes/traits.rs
- native/libcst/src/parser/errors.rs
Updates the native library to use PyO3 0.23. This is the first step towards declaring support for the free-threaded interpreter.
I could have gone further in ripping out `TryIntoPy` in favor of `IntoPyObject`. If you'd prefer not to leave this project in a state with an unnecessary wrapper trait I'm happy to implement that, I just wanted to make the smallest possible working diff.
This passes the tests for me locally. Let's see if CI spots and issues.
> Update for Pyo3 0.23

- .github/workflows/ci.yml
- pyproject.toml
xref #1242 
passes CI on my fork: https://github.com/ngoldbaum/LibCST/actions/runs/13817416645
Is adding `dev-without-jupyter` in `pyproject.toml` ok? It seemed like the cleanest way to handle avoiding jupyter. You could also split `dev` into `tests` and `docs` but I'm not sure how to sort the dependencies.
The windows 3.13t CI is pretty slow but I think most of that is just installing Python and once the cache populates it should be faster.
I'm pinning to an unreleased version of `setup-python` - hopefully Github does a release with free-threaded support soon.
> add free-threaded CI

- native/Cargo.lock
Bump the PyO3 version, as suggested in #1306.
`cargo test` in `native` subdirectory.
> Bump PyO3 to 0.23.5

- .github/workflows/ci.yml
It turns out this isn't necessary: https://github.com/ngoldbaum/LibCST/actions/runs/13838495891
> don't use --no-build-isolation for free-threaded CI

- .github/workflows/build.yml
Basically fixes #1279 by bumping minimum MacOS version from `10.9` (`cibuildwheel` default) to `10.12`.
`Rustc` requires `MACOSX_DEPLOYMENT_TARGET >= 3.12` while `cibuildwheel` sets the `MACOSX_DEPLOYMENT_TARGET` to `10.9` by default, if not specified by the user.
ref 0: [cibuildwheel/macos.py](https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/macos.py#L285-L306)
ref 1: [rustc/src/platform-support/apple-darwin.md](https://github.com/rust-lang/rust/blob/d8e44b722a93e55cbc9a8188dfbfe3faf1226096/src/doc/rustc/src/platform-support/apple-darwin.md?plain=1#L33C1-L37C10)
> ci: enable macos intel wheels

- .github/workflows/ci.yml
5.5.0 added support for `3.13t`: https://github.com/actions/setup-python/releases/tag/v5.5.0
> use released version of setup-python

- libcst/tool.py
Right now if you have an empty formatter list, you'll crash on this line:
```
goldbaum at Nathans-MBP in ~/Documents/numpy on format-to-fstring
± python3 -m libcst.tool codemod --no-format convert_format_to_fstring.ConvertFormatStringCommand .
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/Users/goldbaum/.pyenv/versions/3.13.2/lib/python3.13/site-packages/libcst/tool.py", line 688, in <module>
main(os.environ.get("LIBCST_TOOL_COMMAND_NAME", "libcst.tool"), sys.argv[1:])
~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/goldbaum/.pyenv/versions/3.13.2/lib/python3.13/site-packages/libcst/tool.py", line 683, in main
return lookup.get(args.action or None, …
```
> allow configuring empty formatter lists in codemod CLI

- native/Cargo.lock
- native/libcst/Cargo.toml
- native/libcst/src/nodes/parser_config.rs
- native/libcst_derive/src/into_py.rs
Fixing the deprecations is needed to try testing with Python 3.14 on a pending PR to pyo3's main branch.
> update pyo3 to 0.25

- .github/workflows/build.yml
- pyproject.toml
ci: build windows arm64 wheels
> ci: build windows arm64 wheels

- libcst/codemod/_cli.py
- libcst/codemod/_dummy_pool.py
Replace multiprocessing with ProcessPoolExecutor
Instead of relying on `multiprocessing.Pool`, this PR replaces the implementation of `parallel_exec_transform_with_prettyprint` with `concurrent.futures.ProcessPoolExecutor`
> Replace multiprocessing with ProcessPoolExecutor

- .github/workflows/ci.yml
- libcst/codemod/_cli.py
- libcst/codemod/_dummy_pool.py
- native/libcst/src/py.rs
- pyproject.toml
Enable support for free-threading
This PR:
1. marks the `libcst.native` module as free-threading-compatible
2. replaces the use of ProcessPoolExecutor with ThreadPoolExecutor if free-threaded CPython is detected at runtime
This depends on #1294 and #1289.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Instagram/LibCST/pull/1295).
* #1333
* __->__ #1295
> Enable support for free-threading

- libcst/codemod/_cli.py
#1295 introduced a bug where libcst would use a `ThreadPool` if the GIL was enabled. That's clearly the wrong thing to do :)
> Use ThreadPool if GIL is disabled

- libcst/codegen/gen_matcher_classes.py
- libcst/codegen/tests/test_codegen_clean.py
codegen: Support pipe syntax for Union types
From 3.14 onwards, we'll get `foo | bar` instead of `typing.Union[foo, bar]` as the annotation for union types (including optional). This PR prepares the codegen script for this.
> codegen: Support pipe syntax for Union types

- pyproject.toml
Use poe as a task runner
Make `hatch run foo` wrap the corresponding `poe` command.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Instagram/LibCST/pull/1355).
* #1356
* __->__ #1355
> Use poe as a task runner

- .github/workflows/ci.yml
- .github/workflows/pypi_upload.yml
- .pyre_configuration
- CONTRIBUTING.md
- README.rst
- pyproject.toml
- uv.lock
Switch from hatch to uv
* use dependency-groups in pyproject.toml
* replace `hatch run foo` with `uv run poe foo`
* install uv @ 0.7.12 in CI and disable caching
* use `uv run --group docs` for the `docs` command
* DRY docs between CONTRIBUTING and README
* tell pyre to ignore `.venv`
* set up uv to rebuild on rust, pyproject.toml, git changes
> Switch from hatch to uv

- pyproject.toml
- uv.lock
Missing typing-extensions breaks "from libcst.codemod import CodemodContext"
This can be verified by 
```shell
uv run --python 3.9 --with libcst==1.8.1 python -c "from libcst.codemod import CodemodContext"
```
it raises the following error
```
from typing_extensions import ParamSpec
ModuleNotFoundError: No module named 'typing_extensions'
```
while it works fine for 3.10
```shell
uv run --python 3.10 --with libcst==1.8.1 python -c "from libcst.codemod import CodemodContext"
```
> fix(dependency): add back typing-extensions for 3.9

- native/Cargo.lock
- native/libcst/Cargo.toml
This addresses a crash on 3.14 in 32bit Linux environments
> bump pyo3 to 0.25.1

- libcst/_parser/parso/python/token.py
- libcst/_parser/types/token.py
At Sonar, we are working on suppressing linter issues on lines containing comments starting with `noqa`.
Doing so, and testing it on your source code, it seems that two of the `noqa` comments are missing `:` before the rule ID. 
Then, all issues on these lines are suppressed, rather than only the issue with the specific rule ID. I guess this was not the intent, and I propose to correct it.
> Fix `noqa` comments

- libcst/_nodes/statement.py
- libcst/metadata/tests/test_position_provider.py
(This is a rebase of https://github.com/Instagram/LibCST/pull/1369)
Fixes https://github.com/Instagram/LibCST/issues/1322 where PositionProvider does not provide positions for whitespace. The issue seems to be that when there is no pattern for whitespace nodes during codegen, then they are not included in the position metadata.
* Added a test
* Verified this test failed
* Implemented fix and verified fix
> fixes match statements to work with PositionProvider

- libcst/_nodes/tests/test_try.py
- native/libcst/src/parser/grammar.rs
- native/libcst/tests/fixtures/terrible_tries.py
- test.py
PEP758 removes the requirement for parentheses to surround exceptions in except and except* expressions when 'as' is not present.
This pr implements support for parsing these types of statements
tests are included
> feat: add support for PEP758

- libcst/_parser/entrypoints.py
- libcst/tests/test_import.py
Fixes circular import in libcst
before:
```
thon -m unittest libcst/tests/test_import.py
E
======================================================================
ERROR: libcst (unittest.loader._FailedTest.libcst)
ImportError: Failed to import test module: libcst
File "/usr/local/fbcode/platform010/Python3.12.framework/Versions/3.12/lib/python3.12/unittest/loader.py", line 137, in loadTestsFromName
module = __import__(module_name)
^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/martinli/code/LibCST/libcst/__init__.py", line 216, in <module>
from libcst._parser.entrypoints import parse_expression, parse_module, parse_statement
File "/Users/martinli/code/LibCST/libcst/_parser/entrypoints.py", line …
```
> fix: circular import error
